// Electron main process for the DW:U recreation (openDWU).
//
// Serves the built game (dist/) over a privileged custom scheme, dwu://app/…,
// and maps dwu://app/assets/dwu/<path> to <DW:U install dir>/<path> so the
// renderer can fetch original data/art by URL exactly like it does under
// `npm run dev` (where Vite serves the public/assets/dwu symlink). PNG/JPEG
// art is served without its embedded colour profile (colorProfile.cjs), as
// the original decodes it.
//
// Nothing from the original game ships with the app: the install-derived
// listings the browser cannot make (asset-manifest.json, theme-manifest/) are
// built here from the player's install folder at launch and whenever the
// folder changes (assetManifest.cjs, themeIndex.cjs), and served from memory.
//
// Also here: finding the install (installDir.cjs) or asking for it in the
// setup window (setup.html), the menu (game folder, update check), and the
// daily update check against GitHub Releases (updateCheck.cjs).
//
// The renderer stays platform-neutral: no Node APIs in src/, everything goes
// through URLs under /assets/dwu/.

const { app, BrowserWindow, Menu, dialog, protocol, net, nativeImage, ipcMain, shell } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const { execFileSync } = require('node:child_process');
const { pathToFileURL } = require('node:url');
const { stripColorProfile, isProfiledImagePath } = require('./colorProfile.cjs');
const themeIndex = require('./themeIndex.cjs');
const { buildAssetManifest } = require('./assetManifest.cjs');
const { createResolver } = require('./resolvePath.cjs');
const installLib = require('./installDir.cjs');
const updates = require('./updateCheck.cjs');

// dist/ lives next to desktop/ in the repo; when packaged it is copied into
// resources/ by @electron/packager (extraResource in scripts/package-desktop.mjs).
const DIST_DIR = app.isPackaged ? path.join(process.resourcesPath, 'dwu-dist') : path.join(__dirname, '..', 'dist');
// Our own app icon (generated by scripts/make-icon.mjs at packaging time); absent when running unpackaged.
const OWN_ICON = app.isPackaged ? path.join(process.resourcesPath, 'icon.png') : null;

// The packaged app's package.json is the stage one written by package-desktop.mjs (version from game/package.json);
// unpackaged it is game/package.json.
const PKG = (() => {
    try {
        return require('../package.json');
    } catch {
        return {};
    }
})();
const APP_VERSION = app.isPackaged ? app.getVersion() : String(PKG.version ?? app.getVersion());
const UPDATE_REPO = updates.repoSlug(PKG.repository) ?? 'jfj-oss/openDWU';
const APP_ID = 'local.dwureup.dwu';
const PRODUCT = 'openDWU';
// Where the shell menu is, for the setup window's hint (macOS: the app menu, titled with the product name).
const MENU_SHORTCUT_LABEL = process.platform === 'darwin' ? `the ${app.name} menu` : 'Ctrl+Shift+O';

const CONFIG_FILE = () => path.join(app.getPath('userData'), 'config.json');

// ---------------------------------------------------------------------------
// config.json: { installDir, lastUpdateCheck, skippedVersion, checkForUpdates }
// ---------------------------------------------------------------------------

function readConfig() {
    try {
        const cfg = JSON.parse(fs.readFileSync(CONFIG_FILE(), 'utf8'));
        return cfg && typeof cfg === 'object' && !Array.isArray(cfg) ? cfg : {};
    } catch {
        return {}; // missing or invalid config.json
    }
}

function updateConfig(patch) {
    const cfg = { ...readConfig(), ...patch };
    try {
        fs.mkdirSync(path.dirname(CONFIG_FILE()), { recursive: true });
        const tmp = `${CONFIG_FILE()}.tmp`;
        fs.writeFileSync(tmp, JSON.stringify(cfg, null, 2) + '\n');
        fs.renameSync(tmp, CONFIG_FILE());
    } catch (err) {
        console.warn(`Could not write ${CONFIG_FILE()}: ${err.message}`);
    }
    return cfg;
}

// ---------------------------------------------------------------------------
// Install-dir discovery
// ---------------------------------------------------------------------------

/** Windows registry string value via reg.exe (no native modules), or null. */
function readRegistry(key, value) {
    if (process.platform !== 'win32') return null;
    try {
        const out = execFileSync('reg', ['query', key, '/v', value], { encoding: 'utf8', timeout: 3000, windowsHide: true, stdio: ['ignore', 'pipe', 'ignore'] });
        return installLib.parseRegQueryValue(out, value);
    } catch {
        return null; // key or value absent
    }
}

function candidateOpts() {
    return { platform: process.platform, home: os.homedir(), env: process.env, registry: readRegistry };
}

/**
 * Find the DW:U install dir without asking: $DWU_DIR (not saved; for scripts/tests, same variable as
 * `npm run import-assets`) → saved config → the platform's usual places (saved when found).
 * Returns { dir, previous }: previous is a saved folder that is no longer valid (for the setup window's message).
 */
function discoverInstallDir() {
    const envDir = process.env.DWU_DIR;
    if (envDir) {
        if (installLib.checkInstallDirExact(envDir).ok) return { dir: envDir, previous: null };
        console.warn(`DWU_DIR=${envDir} is not a DW:U install folder (needs images/ and races.txt); ignoring it.`);
    }
    const saved = readConfig().installDir;
    if (typeof saved === 'string' && installLib.checkInstallDirExact(saved).ok) return { dir: saved, previous: null };
    const found = installLib.findInstallDir(candidateOpts());
    if (found) {
        updateConfig({ installDir: found });
        return { dir: found, previous: null };
    }
    return { dir: null, previous: typeof saved === 'string' ? saved : null };
}

// ---------------------------------------------------------------------------
// The current install and everything derived from it
// ---------------------------------------------------------------------------

let installDir = null;
let appIcon = nativeImage.createEmpty();
const resolver = createResolver();
const distResolver = createResolver();
/** Built at launch / on folder change: the JSON bodies of asset-manifest.json and theme-manifest/*. */
let assetManifestBody = '{}';
const themeBodies = new Map(); // name ('index.json' | '<set>.json') -> body | null (404)

function setInstallDir(dir) {
    installDir = dir;
    resolver.clearCache();
    themeBodies.clear();
    const t0 = Date.now();
    assetManifestBody = dir ? JSON.stringify(buildAssetManifest(dir)) : '{}';
    if (dir) {
        const themes = themeIndex.listThemes(dir);
        themeBodies.set('index.json', JSON.stringify(themes));
        for (const t of themes) {
            const idx = themeIndex.buildThemeIndex(dir, t);
            themeBodies.set(`${t}.json`, idx === null ? null : JSON.stringify(idx));
        }
        console.log(`[install] ${dir}: asset manifest ${Math.round(assetManifestBody.length / 1024)} KB, ${themes.length} theme(s) in ${Date.now() - t0} ms`);
    }
    appIcon = makeAppIcon(dir);
    for (const win of BrowserWindow.getAllWindows()) if (!appIcon.isEmpty()) win.setIcon?.(appIcon);
    if (process.platform === 'darwin' && !appIcon.isEmpty()) app.dock?.setIcon(appIcon);
}

/** theme-manifest/<name>: from the table built in setInstallDir; a theme added since is indexed on first request. */
function themeBody(name) {
    if (!installDir) return name === 'index.json' ? '[]' : null;
    if (themeBodies.has(name)) return themeBodies.get(name);
    let body = null;
    if (name.endsWith('.json')) {
        const idx = themeIndex.buildThemeIndex(installDir, name.slice(0, -'.json'.length));
        if (idx !== null) body = JSON.stringify(idx);
    }
    themeBodies.set(name, body);
    return body;
}

// ---------------------------------------------------------------------------
// dwu:// scheme handler
// ---------------------------------------------------------------------------

const json = (body) => new Response(body, { status: 200, headers: { 'Content-Type': 'application/json' } });

// Must be registered after app ready: protocol.handle touches the default
// session, which is only available once the app is ready.
app.whenReady().then(() => {
    protocol.handle('dwu', async (request) => {
        try {
            const url = new URL(request.url);
            // dwu://app/<rest> — host is "app", pathname starts with "/"
            let rest = decodeURIComponent(url.pathname.replace(/^\/+/, ''));
            // The query string (?autostart=1 etc.) is for the page, not the file.

            if (rest.startsWith('assets/dwu/')) {
                // Original DW:U data/art from the user's install folder.
                if (!installDir) {
                    return new Response('DW:U install folder not configured', { status: 503 });
                }
                const fileRel = rest.slice('assets/dwu/'.length);
                const resolved = resolver.resolveInsideRoot(installDir, fileRel);
                if (!resolved) {
                    return new Response(`Not found: ${fileRel}`, { status: 404 });
                }
                if (!fs.statSync(resolved).isFile()) {
                    return new Response(`Not a file: ${fileRel}`, { status: 404 });
                }
                if (isProfiledImagePath(resolved)) {
                    // Original art with its embedded colour profile removed: the original's GDI+ load ignores it,
                    // so the renderer must decode raw values too (desktop/colorProfile.cjs; same as the Vite dev
                    // server's /assets/dwu/ middleware in vite.config.ts).
                    const body = stripColorProfile(await fs.promises.readFile(resolved));
                    const type = /\.png$/i.test(resolved) ? 'image/png' : 'image/jpeg';
                    return new Response(body, { status: 200, headers: { 'Content-Type': type, 'Content-Length': String(body.length) } });
                }
                return net.fetch(pathToFileURL(resolved).href, request);
            }

            if (rest === 'asset-manifest.json') {
                // Folder listings of the USER's install (desktop/assetManifest.cjs), built in setInstallDir; {} without
                // one, like the dev server's manifest when no install is linked.
                return json(assetManifestBody);
            }

            if (rest.startsWith('theme-manifest/')) {
                // Themes of the USER's install (Customization subfolders + each one's file index). desktop/themeIndex.cjs.
                const body = themeBody(rest.slice('theme-manifest/'.length));
                if (body === null) return new Response(`Not found: ${rest}`, { status: 404 });
                return json(body);
            }

            // Everything else: the built game from dist/.
            const resolved = distResolver.resolveInsideRoot(DIST_DIR, rest || 'index.html');
            if (!resolved || !fs.existsSync(resolved) || !fs.statSync(resolved).isFile()) {
                return new Response(`Not found: ${rest}`, { status: 404 });
            }
            // The page itself carries the machine's total RAM (src/systemMemory.ts: the sim-worker default needs
            // 16 GB+; navigator.deviceMemory is capped at 8).
            if ((rest || 'index.html') === 'index.html') {
                const gib = (os.totalmem() / 2 ** 30).toFixed(1);
                const html = (await fs.promises.readFile(resolved, 'utf8')).replace('</head>', `<meta name="dwu-system-memory-gib" content="${gib}">\n</head>`);
                return new Response(html, { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
            }
            return net.fetch(pathToFileURL(resolved).href, request);
        } catch (err) {
            console.error('dwu:// handler error:', err);
            return new Response(String(err && err.message ? err.message : err), { status: 500 });
        }
    });
});

// ---------------------------------------------------------------------------
// Window icon (loaded at runtime from the user's DW:U install folder — art
// can't be committed to the repo — else our own generated icon)
// ---------------------------------------------------------------------------

/**
 * Build the window/dock icon from the install dir. Tries the in-game chrome icon first, then the desktop icon shipped
 * with the game, then the app's own icon. Returns an empty nativeImage if none exists (callers must check isEmpty()).
 */
function makeAppIcon(dir) {
    if (dir) {
        for (const rel of ['images/ui/chrome/galaxy_Icon.png', 'DesktopIcon.ico']) {
            const resolved = resolver.resolveInsideRoot(dir, rel);
            if (!resolved || !fs.existsSync(resolved)) continue;
            const img = nativeImage.createFromPath(resolved);
            if (!img.isEmpty()) return img;
        }
    }
    if (OWN_ICON && fs.existsSync(OWN_ICON)) {
        const img = nativeImage.createFromPath(OWN_ICON);
        if (!img.isEmpty()) return img;
    }
    return nativeImage.createEmpty();
}

// ---------------------------------------------------------------------------
// Setup window: pick / change the install folder (desktop/setup.html)
// ---------------------------------------------------------------------------

let setupWin = null;
let setupState = null; // { mode, previous, promise, done, finish(result) }

/** Show the setup window. mode 'first-run' resolves 'ok' | 'skip' | 'quit'; mode 'change' resolves 'ok' | 'cancel'. */
function openSetupWindow(mode, previous = null) {
    if (setupWin && !setupWin.isDestroyed()) {
        setupWin.focus();
        return setupState.promise;
    }
    const parent = mode === 'change' ? mainWin ?? undefined : undefined;
    setupWin = new BrowserWindow({
        width: 760,
        height: process.platform === 'darwin' ? 720 : 680,
        minWidth: 560,
        minHeight: 520,
        title: `${PRODUCT} — Distant Worlds: Universe folder`,
        backgroundColor: '#0b1220',
        show: false,
        parent,
        modal: mode === 'change' && process.platform !== 'linux', // Linux WMs handle modal children poorly
        icon: appIcon.isEmpty() ? undefined : appIcon,
        autoHideMenuBar: true,
        webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true, preload: path.join(__dirname, 'setupPreload.cjs') },
    });
    setupWin.setMenuBarVisibility(false);
    const win = setupWin;
    let resolveFn;
    const promise = new Promise((r) => (resolveFn = r));
    const state = { mode, previous, promise, done: false };
    state.finish = (result) => {
        if (state.done) return;
        state.done = true;
        resolveFn(result);
        if (!win.isDestroyed()) win.close();
    };
    setupState = state;
    // Closing the window = Quit (first run) / Cancel (change).
    win.on('closed', () => {
        state.finish(mode === 'first-run' ? 'quit' : 'cancel');
        if (setupWin === win) setupWin = null;
    });
    // Links in the page open in the browser, never in the app.
    win.webContents.setWindowOpenHandler(({ url }) => {
        if (updates.isSafeGithubUrl(url) || /^https:\/\/(store\.steampowered\.com|getwhisky\.app|www\.codeweavers\.com)\//.test(url)) shell.openExternal(url);
        return { action: 'deny' };
    });
    win.webContents.on('will-navigate', (e) => e.preventDefault());
    win.once('ready-to-show', () => win.show());
    win.loadFile(path.join(__dirname, 'setup.html'));
    return promise;
}

function fromSetupWindow(event) {
    return setupWin && !setupWin.isDestroyed() && event.sender === setupWin.webContents;
}

function setupInfo() {
    return {
        mode: setupState?.mode ?? 'first-run',
        platform: process.platform,
        current: installDir,
        previous: setupState?.previous ?? null,
        searched: installLib.installCandidates(candidateOpts()).length,
        version: APP_VERSION,
        menuHint: MENU_SHORTCUT_LABEL,
        home: os.homedir(),
    };
}

// The main menu's Check for Updates (gamePreload.cjs): the manual check, from the game window only.
ipcMain.handle('dwu:check-updates', async (event) => {
    if (mainWin === null || event.sender !== mainWin.webContents) return false;
    await checkForUpdates({ manual: true });
    return true;
});
ipcMain.handle('dwu-setup:info', (event) => (fromSetupWindow(event) ? setupInfo() : null));
ipcMain.handle('dwu-setup:browse', async (event, start) => {
    if (!fromSetupWindow(event)) return null;
    const result = await dialog.showOpenDialog(setupWin, {
        title: 'Choose your Distant Worlds: Universe folder',
        buttonLabel: 'Choose',
        defaultPath: typeof start === 'string' && start !== '' && fs.existsSync(start) ? start : installDir ?? os.homedir(),
        properties: ['openDirectory', 'showHiddenFiles', 'dontAddToRecent'],
    });
    if (result.canceled || result.filePaths.length === 0) return null;
    return result.filePaths[0];
});
ipcMain.handle('dwu-setup:check', (event, dir) => {
    if (!fromSetupWindow(event)) return null;
    return installLib.checkInstallDir(typeof dir === 'string' ? dir.trim() : '');
});
ipcMain.handle('dwu-setup:use', (event, dir) => {
    if (!fromSetupWindow(event)) return null;
    const check = installLib.checkInstallDir(typeof dir === 'string' ? dir.trim() : '');
    if (!check.ok) return check;
    updateConfig({ installDir: check.dir });
    const changed = check.dir !== installDir;
    setInstallDir(check.dir);
    console.log(`[setup] install folder set: ${check.dir}`);
    setupState.finish('ok');
    if (changed && mainWin && !mainWin.isDestroyed()) mainWin.webContents.reload(); // the game reloads its data
    return check;
});
ipcMain.handle('dwu-setup:skip', (event) => {
    if (fromSetupWindow(event)) setupState.finish(setupState.mode === 'first-run' ? 'skip' : 'cancel');
});
ipcMain.handle('dwu-setup:quit', (event) => {
    if (fromSetupWindow(event)) setupState.finish(setupState.mode === 'first-run' ? 'quit' : 'cancel');
});

// ---------------------------------------------------------------------------
// Update check (GitHub Releases; desktop/updateCheck.cjs)
// ---------------------------------------------------------------------------

/** How this copy was installed, for picking the matching download. */
function installKind() {
    if (process.platform === 'linux' && process.env.APPIMAGE) return 'appimage';
    if (process.platform === 'win32') {
        // electron-builder's NSIS installer puts its uninstaller next to the exe.
        try {
            if (fs.readdirSync(path.dirname(process.execPath)).some((f) => /^Uninstall .*\.exe$/i.test(f))) return 'nsis';
        } catch {
            // fall through
        }
    }
    return 'archive';
}

function updateChecksEnabled() {
    if (process.env.DWU_UPDATE_CHECK === '0') return false;
    if (readConfig().checkForUpdates === false) return false;
    // Unpackaged runs (npm run desktop:dev) never check unless a test points them at a fake API.
    return app.isPackaged || !!process.env.DWU_UPDATE_URL;
}

let updateCheckRunning = false;

/** Check GitHub for a newer release. manual: from the menu (always runs, reports "up to date" and errors). */
async function checkForUpdates({ manual }) {
    if (updateCheckRunning) return;
    if (!manual) {
        if (!updateChecksEnabled()) return;
        if (!updates.isCheckDue(readConfig().lastUpdateCheck, Date.now())) {
            console.log('[update] checked less than a day ago; skipping');
            return;
        }
    }
    updateCheckRunning = true;
    const apiUrl = process.env.DWU_UPDATE_URL || updates.latestReleaseApiUrl(UPDATE_REPO);
    try {
        console.log(`[update] checking ${apiUrl} (running ${APP_VERSION})`);
        const ctrl = new AbortController();
        const timer = setTimeout(() => ctrl.abort(), 15000);
        let res;
        try {
            res = await net.fetch(apiUrl, {
                headers: { Accept: 'application/vnd.github+json', 'User-Agent': `${PRODUCT}/${APP_VERSION} (${process.platform}-${process.arch})`, 'X-GitHub-Api-Version': '2022-11-28' },
                signal: ctrl.signal,
                cache: 'no-store',
            });
        } finally {
            clearTimeout(timer);
        }
        updateConfig({ lastUpdateCheck: Date.now() });
        if (res.status === 404) {
            console.log('[update] no published release yet');
            if (manual) await showMessage({ type: 'info', message: 'No releases published yet', detail: `You are running ${PRODUCT} ${APP_VERSION}.` });
            return;
        }
        if (!res.ok) throw new Error(`GitHub answered HTTP ${res.status}`);
        const release = updates.releaseInfo(await res.json());
        if (!release) throw new Error('unexpected answer from GitHub');
        const newer = updates.compareVersions(release.version, APP_VERSION) > 0;
        console.log(`[update] latest release ${release.version}: ${newer ? 'newer' : 'not newer'}`);
        if (!newer) {
            if (manual) await showMessage({ type: 'info', message: `${PRODUCT} is up to date`, detail: `You are running ${APP_VERSION}, the latest release.` });
            return;
        }
        if (!manual && readConfig().skippedVersion === release.version) {
            console.log(`[update] ${release.version} was skipped by the player`);
            return;
        }
        const download = updates.pickDownload(release, { platform: process.platform, arch: process.arch, kind: installKind() });
        console.log(`[update] offering ${download ? download.name : release.pageUrl ?? '(no download)'}`);
        const notes = updates.notesExcerpt(release.notes);
        const { response } = await showMessage({
            type: 'info',
            buttons: ['Download', 'Later', 'Skip This Version'],
            defaultId: 0,
            cancelId: 1,
            message: `${PRODUCT} ${release.version} is available`,
            detail:
                `You have ${APP_VERSION}. ${download ? `Download opens ${download.name} in your browser` : 'Download opens the release page in your browser'}; ` +
                `install it over this copy (your game folder setting and saves are kept).` +
                (notes ? `\n\n${notes}` : ''),
        });
        if (response === 0) {
            const target = download?.url ?? release.pageUrl;
            if (target && updates.isSafeGithubUrl(target)) await shell.openExternal(target);
        } else if (response === 2) {
            updateConfig({ skippedVersion: release.version });
        }
    } catch (err) {
        console.warn(`[update] check failed: ${err && err.message ? err.message : err}`);
        if (manual) await showMessage({ type: 'warning', message: 'Could not check for updates', detail: String(err && err.message ? err.message : err) });
    } finally {
        updateCheckRunning = false;
    }
}

function showMessage(opts) {
    const parent = mainWin && !mainWin.isDestroyed() ? mainWin : undefined;
    const o = { title: PRODUCT, buttons: ['OK'], ...opts };
    return parent ? dialog.showMessageBox(parent, o) : dialog.showMessageBox(o);
}

// ---------------------------------------------------------------------------
// Menu: macOS app menu; on Windows/Linux (no menu bar) the same items pop up on Ctrl+Shift+O
// ---------------------------------------------------------------------------

function shellItems() {
    return [
        { label: 'Game Folder…', click: () => openSetupWindow('change') },
        { label: 'Check for Updates…', click: () => checkForUpdates({ manual: true }) },
    ];
}

function showAbout() {
    showMessage({
        type: 'info',
        message: `${PRODUCT} ${APP_VERSION}`,
        detail:
            `A recreation of Distant Worlds: Universe.\n\nGame folder: ${installDir ?? '(none: placeholder art)'}\n` +
            `Electron ${process.versions.electron}, ${process.platform}-${process.arch}\n\nhttps://github.com/${UPDATE_REPO}`,
        buttons: ['OK', 'Open Project Page'],
    }).then(({ response }) => {
        if (response === 1) shell.openExternal(`https://github.com/${UPDATE_REPO}`);
    });
}

function buildMacMenu() {
    // Electron's default menu (File / Edit / View / Window keep their roles and Cmd shortcuts) with our items in the
    // app menu and project links under Help.
    return Menu.buildFromTemplate([
        {
            label: app.name,
            submenu: [
                { label: `About ${PRODUCT}`, click: showAbout },
                { type: 'separator' },
                ...shellItems(),
                { type: 'separator' },
                { role: 'services' },
                { type: 'separator' },
                { role: 'hide' },
                { role: 'hideOthers' },
                { role: 'unhide' },
                { type: 'separator' },
                { role: 'quit' },
            ],
        },
        { role: 'fileMenu' },
        { role: 'editMenu' },
        { role: 'viewMenu' },
        { role: 'windowMenu' },
        {
            role: 'help',
            submenu: [
                { label: `${PRODUCT} on GitHub`, click: () => shell.openExternal(`https://github.com/${UPDATE_REPO}`) },
                { label: 'Releases', click: () => shell.openExternal(`https://github.com/${UPDATE_REPO}/releases`) },
            ],
        },
    ]);
}

function popupShellMenu(win) {
    Menu.buildFromTemplate([
        ...shellItems(),
        { type: 'separator' },
        { label: 'Toggle Full Screen', accelerator: 'F11', click: () => toggleFullscreen(win) },
        { label: `About ${PRODUCT}`, click: showAbout },
        { type: 'separator' },
        { label: 'Quit', click: () => app.quit() },
    ]).popup({ window: win });
}

// ---------------------------------------------------------------------------
// Main window
// ---------------------------------------------------------------------------

let mainWin = null;

function toggleFullscreen(win) {
    win.setFullScreen(!win.isFullScreen());
}

function createWindow() {
    const win = new BrowserWindow({
        width: 1600,
        height: 900,
        minWidth: 1280,
        minHeight: 720,
        title: 'Distant Worlds: Universe',
        backgroundColor: '#000',
        show: false,
        // Window icon on Linux/Windows (macOS ignores `icon`; the dock icon is
        // set via app.dock.setIcon in setInstallDir). Empty image = Electron default.
        icon: appIcon.isEmpty() ? undefined : appIcon,
        webPreferences: {
            contextIsolation: true,
            nodeIntegration: false,
            sandbox: true,
            preload: path.join(__dirname, 'gamePreload.cjs'),
        },
    });
    mainWin = win;
    win.on('closed', () => {
        if (mainWin === win) mainWin = null;
    });

    // The game page died (out of memory, a crash, killed): instead of leaving a black window, log why and offer a
    // reload. The last autosave or manual save is where to continue from.
    // The page's last warnings / errors and its memory, kept for the crash log (a crash leaves no other trace).
    const recentConsole = [];
    let lastMemory = '';
    win.webContents.on('console-message', (event, ...legacy) => {
        // Electron 44: event.level is 'warning' / 'error' / ...; older: (event, level, message).
        const level = event.level ?? (['verbose', 'info', 'warning', 'error'][legacy[0]] || String(legacy[0]));
        const message = event.message ?? legacy[1];
        if (level !== 'warning' && level !== 'error') return;
        const entry = `${new Date().toISOString()} [${level}] ${String(message).slice(0, 500)}`;
        recentConsole.push(entry);
        if (recentConsole.length > 40) recentConsole.shift();
        // The sim worker stopping (it crashed, ran out of memory — V8 kills only its isolate, the page lives on and
        // reports it after its silence watchdog — or stopped answering) goes to the crash log at once, with the memory:
        // the page may well die of the same cause minutes later, or the player quits from the restart prompt.
        if (level === 'error' && /sim worker: STOPPED|Autosave failed/.test(String(message))) {
            try {
                fs.appendFileSync(path.join(app.getPath('userData'), 'crash-log.txt'), `${entry} version=${APP_VERSION}\n` + (lastMemory !== '' ? `  last memory sample: ${lastMemory}\n` : ''));
            } catch {
                /* best effort */
            }
        }
    });
    const memoryTimer = setInterval(() => {
        try {
            const pid = win.webContents.getOSProcessId();
            const m = app.getAppMetrics().find((x) => x.pid === pid);
            if (m) lastMemory = `${new Date().toISOString()} page working set ${(m.memory.workingSetSize / 1024 / 1024).toFixed(2)} GB, peak ${(m.memory.peakWorkingSetSize / 1024 / 1024).toFixed(2)} GB`;
        } catch {
            /* the page is gone */
        }
    }, 15000);
    win.on('closed', () => clearInterval(memoryTimer));
    win.webContents.on('render-process-gone', async (_event, details) => {
        const line =
            `${new Date().toISOString()} render-process-gone reason=${details.reason} exitCode=${details.exitCode} version=${APP_VERSION}\n` +
            (lastMemory !== '' ? `  last memory sample: ${lastMemory}\n` : '') +
            (recentConsole.length > 0 ? `  last page warnings / errors:\n${recentConsole.map((l) => `    ${l}`).join('\n')}\n` : '');
        recentConsole.length = 0;
        console.error(`[crash] ${line.trim()}`);
        try {
            fs.appendFileSync(path.join(app.getPath('userData'), 'crash-log.txt'), line);
        } catch {
            /* best effort */
        }
        if (win.isDestroyed()) return;
        const oom = details.reason === 'oom';
        const { response } = await showMessage({
            type: 'error',
            buttons: ['Reload', 'Quit'],
            defaultId: 0,
            cancelId: 1,
            message: oom ? 'The game ran out of memory' : 'The game stopped unexpectedly',
            detail:
                `Reason: ${details.reason} (exit code ${details.exitCode}). ` +
                'Reload returns to the main menu; load your last save or autosave to continue. ' +
                `Details are in ${path.join(app.getPath('userData'), 'crash-log.txt')}.`,
        });
        if (response === 0 && !win.isDestroyed()) win.reload();
        else app.quit();
    });

    win.once('ready-to-show', () => {
        win.show();
        // The daily update check, once the game is up (and off the startup path).
        setTimeout(() => checkForUpdates({ manual: false }), 8000);
    });

    // F11 / Ctrl/Cmd+F toggles fullscreen; Ctrl+Shift+O opens the shell menu on Windows/Linux (no menu bar there).
    win.webContents.on('before-input-event', (event, input) => {
        if (input.type !== 'keyDown') return;
        const isF11 = input.key === 'F11';
        const isCtrlCmdF = input.key === 'f' && (input.controlKey || input.metaKey);
        if (isF11 || isCtrlCmdF) {
            toggleFullscreen(win);
        }
        if (process.platform !== 'darwin' && input.control && input.shift && !input.alt && !input.meta && input.key.toLowerCase() === 'o') {
            event.preventDefault(); // the game never sees it
            popupShellMenu(win);
        }
    });

    // Links the game opens (if any) go to the browser; the window itself only ever shows dwu://app/.
    win.webContents.setWindowOpenHandler(({ url }) => {
        if (/^https:\/\//.test(url)) shell.openExternal(url);
        return { action: 'deny' };
    });

    win.loadURL('dwu://app/index.html');
}

// ---------------------------------------------------------------------------
// App lifecycle
// ---------------------------------------------------------------------------

// Privileged scheme registration must happen before app ready.
protocol.registerSchemesAsPrivileged([
    {
        scheme: 'dwu',
        privileges: {
            standard: true,
            secure: true,
            supportFetchAPI: true,
            corsEnabled: true,
            stream: true,
        },
    },
]);

if (process.platform === 'win32') app.setAppUserModelId(APP_ID); // taskbar grouping = the installer's shortcuts

// One instance per profile: a second launch focuses the running window (two would fight over the saves' storage).
if (!app.requestSingleInstanceLock()) {
    app.quit();
} else {
    app.on('second-instance', () => {
        const w = setupWin && !setupWin.isDestroyed() ? setupWin : mainWin;
        if (w) {
            if (w.isMinimized()) w.restore();
            w.focus();
        }
    });

    let launching = true;
    app.whenReady().then(async () => {
        // (protocol.handle for dwu:// is registered in the whenReady above.)
        // No menu bar on Windows/Linux (the shell menu pops up on Ctrl+Shift+O); macOS gets the app menu.
        Menu.setApplicationMenu(process.platform === 'darwin' ? buildMacMenu() : null);

        const found = discoverInstallDir();
        if (found.dir) {
            setInstallDir(found.dir);
        } else {
            setInstallDir(null); // our own icon for the setup window
            const result = await openSetupWindow('first-run', found.previous);
            if (result === 'quit') {
                app.quit();
                return;
            }
            if (!installDir) {
                // Player chose to continue without the game files: the game boots with generated fallbacks.
                console.warn('No DW:U install folder configured; running without original assets.');
            }
        }
        createWindow();
        launching = false;

        app.on('activate', () => {
            if (BrowserWindow.getAllWindows().length === 0) createWindow();
        });
    });

    app.on('window-all-closed', () => {
        // The first-run setup window closing must not quit before the main window opens (a 'quit' answer quits above).
        if (launching) return;
        if (process.platform !== 'darwin') app.quit();
    });
}
