#!/usr/bin/env node
// Seed-pin maintenance (tasks/M4-plan.md §5.3.4). Every seed-dependent exact value in the tests is asserted with
// `expect(actual).toMatchPin('<scenario>.<name>'[, inlineLiteral])` (test/pins/pin.ts); the values live in
// test/pins/seed1.json, or in place as the matcher's second argument where a literal reads better in the test.
//
//   npm run repin -- --reason "<why the pins moved>"   recompute every pin, rewrite seed1.json and the in-place
//                                                        literals, append "Moved <old> → <new>: <reason>" to the
//                                                        reason comment above each moved pin and to test/pins/HISTORY.md
//   npm run repin -- --check                           exit 1 if anything would change (merge gate)
//   npm run repin -- --dry-run                         print what would change, write nothing
//   options: --workers N (vitest --maxWorkers, default 2), --verify (re-run the pinned files normally afterwards),
//            --keep (keep the capture directory)
//
// How values are recomputed: the pinned test files are run with DWU_PIN_CAPTURE=<tmp dir>. In that mode toMatchPin
// records the actual value to <tmp dir> (and passes) instead of asserting, so every pin is recomputed by the test's own
// construction code — no test output is parsed. test/pins/manifest.json lists every pin site (regenerated by this
// script from the toMatchPin calls; --check fails when it is stale).
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const testDir = join(root, 'test');
const pinsDir = join(testDir, 'pins');
const GOLDEN = join(pinsDir, 'seed1.json');
const MANIFEST = join(pinsDir, 'manifest.json');
const HISTORY = join(pinsDir, 'HISTORY.md');

// ---------------------------------------------------------------- arguments
function arg(name, fallback) {
    const i = process.argv.indexOf(`--${name}`);
    if (i < 0) return fallback;
    const v = process.argv[i + 1];
    return v === undefined || v.startsWith('--') ? true : v;
}
const check = arg('check', false) === true;
const dryRun = arg('dry-run', false) === true;
const verify = arg('verify', false) === true;
const keep = arg('keep', false) === true;
const workers = Number(arg('workers', 2));
const reason = typeof arg('reason', null) === 'string' ? arg('reason', null).trim() : null;
const today = new Date().toISOString().slice(0, 10);

// ---------------------------------------------------------------- JSON helpers
/** Key-order-insensitive canonical JSON (toEqual semantics for plain data). */
function canon(v) {
    if (Array.isArray(v)) return `[${v.map(canon).join(',')}]`;
    if (v !== null && typeof v === 'object') return `{${Object.keys(v).sort().map((k) => `${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`;
    return JSON.stringify(v);
}
/** Pretty JSON: containers that fit in `width` columns stay on one line. */
function inline(v) {
    if (Array.isArray(v)) return `[${v.map(inline).join(', ')}]`;
    if (v !== null && typeof v === 'object') return `{${Object.keys(v).map((k) => `${JSON.stringify(k)}: ${inline(v[k])}`).join(', ')}}`;
    return JSON.stringify(v);
}
function pretty(v, indent = '', width = 110) {
    const flat = inline(v);
    if (v === null || typeof v !== 'object' || indent.length + flat.length <= width) return flat;
    const inner = indent + '    ';
    if (Array.isArray(v)) return `[\n${v.map((x) => inner + pretty(x, inner, width)).join(',\n')}\n${indent}]`;
    return `{\n${Object.keys(v).map((k) => `${inner}${JSON.stringify(k)}: ${pretty(v[k], inner, width)}`).join(',\n')}\n${indent}}`;
}
/** Short form of a value for the "Moved <old> → <new>" lines. */
function short(v) {
    if (v === undefined) return '(new)';
    const s = JSON.stringify(v);
    if (s.length <= 40) return s;
    return `#${createHash('sha1').update(canon(v)).digest('hex').slice(0, 10)}`;
}

// ---------------------------------------------------------------- source scanning
function walk(dir, out = []) {
    for (const name of readdirSync(dir)) {
        const p = join(dir, name);
        if (statSync(p).isDirectory()) walk(p, out);
        else if (p.endsWith('.test.ts')) out.push(p);
    }
    return out;
}

/** Offset just past the string / template / comment starting at `i` (or i itself when none starts there). */
function skipNonCode(src, i) {
    const c = src[i];
    if (c === '/' && src[i + 1] === '/') { const e = src.indexOf('\n', i); return e < 0 ? src.length : e; }
    if (c === '/' && src[i + 1] === '*') { const e = src.indexOf('*/', i + 2); return e < 0 ? src.length : e + 2; }
    if (c === "'" || c === '"' || c === '`') {
        let j = i + 1;
        while (j < src.length && src[j] !== c) {
            if (src[j] === '\\') j++;
            else if (c === '`' && src[j] === '$' && src[j + 1] === '{') j = scanBalanced(src, j + 1) - 1;
            j++;
        }
        return j + 1;
    }
    return i;
}
/** `src[open]` is ( [ or {: offset just past its matching closer. */
function scanBalanced(src, open) {
    let depth = 0;
    for (let i = open; i < src.length;) {
        const j = skipNonCode(src, i);
        if (j !== i) { i = j; continue; }
        const c = src[i];
        if (c === '(' || c === '[' || c === '{') depth++;
        else if (c === ')' || c === ']' || c === '}') { depth--; if (depth === 0) return i + 1; }
        i++;
    }
    throw new Error('unbalanced brackets');
}
/** Top-level argument spans of the call whose '(' is at `open`. */
function callArgs(src, open) {
    const end = scanBalanced(src, open) - 1;
    const args = [];
    let depth = 0, start = open + 1;
    for (let i = open + 1; i < end;) {
        const j = skipNonCode(src, i);
        if (j !== i) { i = j; continue; }
        const c = src[i];
        if (c === '(' || c === '[' || c === '{') depth++;
        else if (c === ')' || c === ']' || c === '}') depth--;
        else if (c === ',' && depth === 0) { args.push([start, i]); start = i + 1; }
        i++;
    }
    if (src.slice(start, end).trim() !== '') args.push([start, end]);
    return args.map(([s, e]) => {
        while (/\s/.test(src[s])) s++;
        while (e > s && /\s/.test(src[e - 1])) e--;
        return { start: s, end: e, text: src.slice(s, e) };
    });
}
const lineOf = (src, off) => src.slice(0, off).split('\n').length;

/** Every toMatchPin call in the test tree. */
function scanPins() {
    const pins = [];
    for (const file of walk(testDir).sort()) {
        const src = readFileSync(file, 'utf8');
        const re = /\.toMatchPin\s*\(/g;
        let m;
        while ((m = re.exec(src)) !== null) {
            const open = m.index + m[0].length - 1;
            const args = callArgs(src, open);
            const keyText = args[0]?.text ?? '';
            if (!/^'[A-Za-z0-9_]+\.[A-Za-z0-9_.]+'$/.test(keyText)) {
                throw new Error(`${relative(root, file)}:${lineOf(src, m.index)}: toMatchPin needs a literal '<scenario>.<name>' key`);
            }
            const before = src.slice(0, m.index);
            const its = [...before.matchAll(/\bit\(\s*(['"`])((?:\\.|(?!\1).)*)\1/g)];
            pins.push({
                key: keyText.slice(1, -1),
                kind: args.length > 1 ? 'inline' : 'golden',
                file: relative(root, file),
                line: lineOf(src, m.index),
                test: its.length ? its[its.length - 1][2] : null,
                anchor: src.split('\n')[lineOf(src, m.index) - 1].trim().slice(0, 160),
            });
        }
    }
    return pins;
}

/** Seed-pin shapes that bypass toMatchPin (they would not be repinned). */
function scanLegacy() {
    const hits = [];
    for (const file of walk(testDir).sort()) {
        readFileSync(file, 'utf8').split('\n').forEach((line, i) => {
            const code = line.replace(/\/\/.*$/, '');
            if (/\bPINNED_[A-Z0-9_]+\b/.test(code) || /toBe\(\s*'[0-9a-f]{16}'\s*\)/.test(code)) hits.push(`${relative(root, file)}:${i + 1}: ${line.trim().slice(0, 120)}`);
        });
    }
    return hits;
}

// ---------------------------------------------------------------- source rewriting
/** Replace the in-place literal of `key` and append the reason line above its statement. */
function rewriteInline(src, key, value) {
    const at = src.indexOf(`toMatchPin('${key}'`);
    const args = callArgs(src, src.indexOf('(', at));
    const lit = args[1];
    const lineStart = src.lastIndexOf('\n', lit.start) + 1;
    const indent = /^\s*/.exec(src.slice(lineStart))[0];
    return src.slice(0, lit.start) + pretty(value, indent) + src.slice(lit.end);
}
function appendReason(src, key, line) {
    const lines = src.split('\n');
    const at = lines.findIndex((l) => l.includes(`toMatchPin('${key}'`));
    // The statement starts at the nearest line (at or above) that opens `expect(`.
    let s = at;
    for (let i = at; i >= Math.max(0, at - 40); i--) { if (/\bexpect\s*\(/.test(lines[i])) { s = i; break; } }
    const indent = /^\s*/.exec(lines[s])[0];
    lines.splice(s, 0, `${indent}// ${line}`);
    return lines.join('\n');
}

// ---------------------------------------------------------------- main
const problems = [];
const pins = scanPins();
const byKey = new Map();
for (const p of pins) {
    if (byKey.has(p.key)) problems.push(`duplicate pin key '${p.key}' (${byKey.get(p.key).file}:${byKey.get(p.key).line} and ${p.file}:${p.line})`);
    byKey.set(p.key, p);
}
const golden = existsSync(GOLDEN) ? JSON.parse(readFileSync(GOLDEN, 'utf8')) : {};
const goldenGet = (key) => { const d = key.indexOf('.'); const g = golden[key.slice(0, d)]; return g && Object.prototype.hasOwnProperty.call(g, key.slice(d + 1)) ? { found: true, value: g[key.slice(d + 1)] } : { found: false }; };
for (const [scenario, values] of Object.entries(golden)) {
    for (const name of Object.keys(values)) {
        const p = byKey.get(`${scenario}.${name}`);
        if (!p || p.kind !== 'golden') problems.push(`seed1.json key '${scenario}.${name}' has no toMatchPin('${scenario}.${name}') site`);
    }
}
for (const hit of scanLegacy()) problems.push(`seed pin outside toMatchPin (not repinnable): ${hit}`);

const manifest = {
    note: 'Generated by scripts/repin.mjs from the toMatchPin calls under test/. kind golden: value in test/pins/seed1.json; kind inline: literal kept in place as the second toMatchPin argument (rewritten there by repin). No line numbers, so unrelated test edits do not make it stale.',
    count: pins.length,
    pins: pins.map(({ key, kind, file, test, anchor }) => ({ key, kind, file, test, anchor })),
};
const manifestText = JSON.stringify(manifest, null, 2) + '\n';
const manifestStale = !existsSync(MANIFEST) || readFileSync(MANIFEST, 'utf8') !== manifestText;

// Capture run.
const files = [...new Set(pins.map((p) => p.file))];
const capDir = mkdtempSync(join(tmpdir(), 'dwu-pins-'));
console.log(`[repin] ${pins.length} pins in ${files.length} files; capturing (vitest --maxWorkers=${workers}) ...`);
const t0 = Date.now();
const run = spawnSync('npx', ['vitest', 'run', ...files, `--maxWorkers=${workers}`, '--reporter=dot', '--silent'], {
    cwd: root, env: { ...process.env, DWU_PIN_CAPTURE: capDir }, stdio: ['ignore', 'pipe', 'pipe'], encoding: 'utf8', maxBuffer: 1 << 28,
});
console.log(`[repin] capture run: exit ${run.status} in ${((Date.now() - t0) / 1000).toFixed(0)} s`);
if (run.status !== 0) {
    const out = `${run.stdout}\n${run.stderr}`;
    const failed = [...new Set(out.split('\n').filter((l) => /^\s*(FAIL\s|AssertionError|TypeError|Error:)/.test(l)).map((l) => l.trim().slice(0, 200)))].slice(0, 40);
    problems.push(`vitest failed in capture mode (non-pin assertions or errors):\n    ${failed.join('\n    ')}`);
}

const captured = new Map();
for (const name of readdirSync(capDir)) {
    const c = JSON.parse(readFileSync(join(capDir, name), 'utf8'));
    const prev = captured.get(c.key);
    if (prev && canon(prev.actual) !== canon(c.actual)) problems.push(`pin '${c.key}' captured two different values (non-deterministic or reached twice): ${short(prev.actual)} / ${short(c.actual)}`);
    captured.set(c.key, c);
}
if (!keep) rmSync(capDir, { recursive: true, force: true });
else console.log(`[repin] captures kept in ${capDir}`);

const changes = [];
for (const p of pins) {
    const c = captured.get(p.key);
    if (!c) { problems.push(`pin '${p.key}' (${p.file}:${p.line}) was not reached in the capture run (its test failed or was skipped)`); continue; }
    const old = p.kind === 'golden' ? goldenGet(p.key) : { found: true, value: c.expected };
    if (!old.found || canon(old.value) !== canon(c.actual)) changes.push({ pin: p, old: old.found ? old.value : undefined, value: c.actual });
}

// Report.
for (const ch of changes) {
    const { pin: p } = ch;
    console.log(`[repin] ${p.key} (${p.file}:${p.line}, ${p.kind}): ${short(ch.old)} → ${short(ch.value)}`);
    if (dryRun) {
        const a = pretty(ch.old ?? null).split('\n'), b = pretty(ch.value).split('\n');
        const n = Math.max(a.length, b.length);
        for (let i = 0; i < n; i++) if (a[i] !== b[i]) console.log(`    ${i + 1}: - ${a[i] ?? ''}\n    ${i + 1}: + ${b[i] ?? ''}`);
    }
}
if (manifestStale) console.log('[repin] test/pins/manifest.json is out of date');
for (const pr of problems) console.log(`[repin] PROBLEM: ${pr}`);

if (check || dryRun) {
    const dirty = changes.length > 0 || manifestStale || problems.length > 0;
    console.log(`[repin] ${check ? 'check' : 'dry run'}: ${changes.length} pin(s) would change${manifestStale ? ', manifest stale' : ''}, ${problems.length} problem(s)`);
    process.exit(check && dirty ? 1 : 0);
}

// Write.
if (changes.length > 0 && !reason) {
    console.error('[repin] pins moved: pass --reason "<why>" (it is recorded next to each pin and in test/pins/HISTORY.md)');
    process.exit(2);
}
const oneLineReason = (reason ?? '').replace(/\s+/g, ' ');
const sources = new Map();
const src = (f) => { if (!sources.has(f)) sources.set(f, readFileSync(join(root, f), 'utf8')); return sources.get(f); };
for (const ch of changes) {
    const { pin: p } = ch;
    if (p.kind === 'golden') {
        const d = p.key.indexOf('.');
        (golden[p.key.slice(0, d)] ??= {})[p.key.slice(d + 1)] = ch.value;
    } else {
        sources.set(p.file, rewriteInline(src(p.file), p.key, ch.value));
    }
    sources.set(p.file, appendReason(src(p.file), p.key, `Moved ${short(ch.old)} → ${short(ch.value)}: ${oneLineReason} (${today})`));
}
{ // (always rewritten: keeps the file sorted and in the canonical layout)
    const sorted = Object.fromEntries(Object.keys(golden).sort().map((s) => [s, golden[s]]));
    writeFileSync(GOLDEN, pretty(sorted, '', 120) + '\n');
}
for (const [f, text] of sources) writeFileSync(join(root, f), text);
if (changes.length > 0) {
    const hist = existsSync(HISTORY) ? readFileSync(HISTORY, 'utf8') : '# Seed-pin history\n\nAppended by `npm run repin -- --reason "<why>"` (scripts/repin.mjs).\n';
    const block = [`\n## ${today} — ${oneLineReason}\n`, ...changes.map((ch) => `- \`${ch.pin.key}\` (${ch.pin.file}): Moved ${short(ch.old)} → ${short(ch.value)}: ${oneLineReason}`)].join('\n');
    writeFileSync(HISTORY, hist.replace(/\n*$/, '\n') + block + '\n');
}
// Rewrites move lines: regenerate the manifest from the updated sources.
const finalManifest = { ...manifest, pins: scanPins().map(({ key, kind, file, test, anchor }) => ({ key, kind, file, test, anchor })) };
writeFileSync(MANIFEST, JSON.stringify(finalManifest, null, 2) + '\n');
console.log(`[repin] ${changes.length} pin(s) updated; manifest ${pins.length} pins.`);

if (verify && changes.length > 0) {
    console.log('[repin] verifying the pinned files ...');
    const v = spawnSync('npx', ['vitest', 'run', ...files, `--maxWorkers=${workers}`, '--reporter=dot', '--silent'], { cwd: root, stdio: 'inherit' });
    if (v.status !== 0) problems.push('verification run failed');
}
process.exit(problems.length > 0 ? 1 : 0);
