// [wizardB1] New-game wizard options wired to the engine (Start.1.cs 3685-3850 btnStartNewGameStart_Click, Start.cs 5613
// btnJumpStartTheGalaxyNext_Click → Start.2.cs CreateGameFromSettings → Galaxy.4.cs 2088 ctor): each wizard option maps to
// the original's value, and that value changes the game the way the C# reads it.
import { beforeAll, describe, expect, it } from 'vitest';
import { createGame, ensureAggressiveAiRaces, type ResolvedStart } from '../src/sim/game';
import { Random } from '../src/sim/random';
import { generateGalaxy } from '../src/sim/galaxy';
import { CreatureType } from '../src/sim/creature';
import { PiratePlayStyle, generateNewPirateEmpires } from '../src/sim/pirates';
import { GalaxyShape } from '../src/sim/types';
import {
    aggressionFor,
    alienLifeFor,
    applyEmpireTypeChoice,
    corruptionMultiplierFor,
    defaultStartGameOptions,
    difficultyFor,
    spaceCreaturesFor,
    toCreateGameOptions,
    type StartGameOptions,
} from '../src/sim/startGameOptions';
import { tickGameOptions } from './helpers/tickGame';
import { cachedTickGame } from './helpers/gameCache';
import { loadGameDataFs } from './helpers/loadGameDataFs';
import type { GameData } from '../src/sim/data/gameData';

let gameData: GameData;
beforeAll(async () => {
    gameData = await loadGameDataFs();
}, 60000);

const NAMES = Array.from({ length: 1500 }, (_, i) => `N${i}`);
const start = (o: Partial<StartGameOptions> = {}): StartGameOptions => ({ ...defaultStartGameOptions(), seed: 7, raceName: 'Human', ...o });

describe('wizard slider → Galaxy ctor value (Start.1.cs 3687-3694, 3739)', () => {
    it('maps Alien Life, Space Creatures, Aggression and Difficulty through method_67 / 62 / 71 / 201', () => {
        const life = [150, 250, 400, 700, 1000];
        const creatures = [0.0, 0.3, 0.6, 1.0];
        const aggression = [0.9, 1.1, 1.3, 1.5, 1.7];
        const difficulty = [0.7, 1.0, 1.25, 1.6, 2.0];
        life.forEach((v, i) => expect(toCreateGameOptions(start({ alienLifeIndex: i }), gameData, NAMES).lifePrevalence).toBe(v));
        creatures.forEach((v, i) => expect(toCreateGameOptions(start({ spaceCreaturesIndex: i }), gameData, NAMES).creaturePrevalence).toBe(v));
        aggression.forEach((v, i) => expect(toCreateGameOptions(start({ aggressionIndex: i }), gameData, NAMES).aggressionLevel).toBe(v));
        difficulty.forEach((v, i) => expect(toCreateGameOptions(start({ difficultyIndex: i }), gameData, NAMES).difficultyLevel).toBe(v));
        expect([0, 1, 2, 3, 4].map(alienLifeFor)).toEqual(life);
        expect([0, 1, 2, 3].map(spaceCreaturesFor)).toEqual(creatures);
        expect([0, 1, 2, 3, 4].map(aggressionFor)).toEqual(aggression);
        expect([0, 1, 2, 3, 4].map(difficultyFor)).toEqual(difficulty);
    });

    it('defaults to the original fresh-install positions (Main.Part9.cs method_259): 400 life, 0.6 creatures, aggression 1.1, difficulty 1.0', () => {
        const c = toCreateGameOptions(start(), gameData, NAMES);
        expect(c.lifePrevalence).toBe(400);
        expect(c.creaturePrevalence).toBe(0.6);
        expect(c.aggressionLevel).toBe(1.1);
        expect(c.difficultyLevel).toBe(1.0);
        expect(c.spawnNewEmpires).toBe(true);
        expect(c.allowTechTrading).toBe(true);
        expect(c.allowGiantKaltorGeneration).toBe(true);
        expect(c.destroyedPiratesDoNotRespawn).toBe(false);
        expect(c.autogeneratedAiEmpires).toBe(true);
        // Story box: Distant Worlds + Return of the Shakturi on; Shadows only offered in a PreWarp galaxy.
        expect(c.storyDistantWorldsEnabled).toBe(true);
        expect(c.victoryConditions!.enableStoryEvents).toBe(true);
        expect(c.victoryConditions!.enableStoryEventsShadows).toBe(false);
        expect(toCreateGameOptions(start({ galaxyExpansionIndex: 0 }), gameData, NAMES).victoryConditions!.enableStoryEventsShadows).toBe(true);
        // Corruption: the player's slider (method_63, default Normal = 1.1) and every AI start's EmpireStart default 1.1.
        expect(c.player.corruptionMultiplier).toBe(1.1);
        expect(c.aiEmpires.every((e) => e.corruptionMultiplier === 1.1)).toBe(true);
        expect([0, 1, 2, 3].map(corruptionMultiplierFor)).toEqual([0.9, 1.1, 1.3, 1.5]);
        expect(c.player.homeSystemFavourability).toBe('Normal');
        expect(c.player.startLocation).toBe('(Random)');
        expect(c.player.playAsPirate).toBeUndefined();
    });

    it('passes the option checkboxes, story toggles, home system and start location through', () => {
        const o = start({ spawnNewEmpires: false, allowTechTrading: false, allowGiantKaltorGeneration: false, destroyedPiratesDoNotRespawn: true, homeSystemIndex: 4, startLocationIndex: 3, shape: GalaxyShape.Spiral, empireCorruptionIndex: 3 });
        o.victory = { ...o.victory, enableStoryDistantWorlds: false, enableStoryEvents: false };
        const c = toCreateGameOptions(o, gameData, NAMES);
        expect([c.spawnNewEmpires, c.allowTechTrading, c.allowGiantKaltorGeneration, c.destroyedPiratesDoNotRespawn]).toEqual([false, false, false, true]);
        expect(c.storyDistantWorldsEnabled).toBe(false);
        expect(c.victoryConditions!.enableStoryEvents).toBe(false);
        expect(c.player.homeSystemFavourability).toBe('Excellent');
        expect(c.player.startLocation).toBe('Far Regions');
        expect(c.player.corruptionMultiplier).toBe(1.5);
        // A manual empire list skips method_104.
        o.otherEmpires = { ...o.otherEmpires, manual: [{ race: 'Human', governmentId: -1, name: '' }] };
        expect(toCreateGameOptions(o, gameData, NAMES).autogeneratedAiEmpires).toBe(false);
    });
});

describe('Galaxy ctor values change generation (Galaxy.4.cs 2137-2153)', () => {
    const gen = (o: { creaturePrevalence?: number; lifePrevalence?: number; allowGiantKaltorGeneration?: boolean }) =>
        generateGalaxy({ seed: 3, shape: GalaxyShape.Spiral, starCount: 300, sectorWidth: 8, sectorHeight: 8, systemNames: NAMES, gameData, ...o });

    it('scales the space-creature count with _CreaturePrevalence (Galaxy.6.cs SelectCreatures)', () => {
        const none = gen({ creaturePrevalence: 0.0 });
        const few = gen({ creaturePrevalence: 0.3 });
        const many = gen({ creaturePrevalence: 1.0 });
        expect(none.creaturePrevalence).toBe(0.0);
        expect(none.creatures.length).toBe(0);
        expect(few.creatures.length).toBeGreaterThan(0);
        expect(many.creatures.length).toBeGreaterThan(few.creatures.length * 2);
    }, 120000);

    it('AllowGiantKaltorGeneration = false places no Kaltors', () => {
        const on = gen({ creaturePrevalence: 1.0 });
        const off = gen({ creaturePrevalence: 1.0, allowGiantKaltorGeneration: false });
        expect(on.creatures.some((c) => c.type === CreatureType.Kaltor)).toBe(true);
        expect(off.allowGiantKaltorGeneration).toBe(false);
        expect(off.creatures.some((c) => c.type === CreatureType.Kaltor)).toBe(false);
    }, 120000);

    it('limits independent alien colonies with _LifePrevalence (Galaxy.6.cs CheckIndependentColonyLimitForRace)', () => {
        // SetupAlienRacePopulations needs empire starts for its race regions (SelectPopulation reads the nearest one).
        const empireStarts = gameData.races.filter((r) => r.playable).slice(0, 4).map((resolvedRace) => ({ resolvedRace, projectedColonyAmount: 1 }));
        const rare = generateGalaxy({ seed: 3, shape: GalaxyShape.Spiral, starCount: 300, sectorWidth: 8, sectorHeight: 8, systemNames: NAMES, gameData, empireStarts, lifePrevalence: 150 });
        const common = generateGalaxy({ seed: 3, shape: GalaxyShape.Spiral, starCount: 300, sectorWidth: 8, sectorHeight: 8, systemNames: NAMES, gameData, empireStarts, lifePrevalence: 1000 });
        expect(common.independentCount).toBeGreaterThan(0);
        expect(rare.lifePrevalence).toBe(150);
        expect(rare.independentCount).toBeLessThan(common.independentCount);
        expect(() => gen({ lifePrevalence: 0 })).toThrow(RangeError);
    }, 120000);

    it('unset options keep the C# ctor defaults (the harness game is unchanged)', () => {
        const g = gen({});
        expect([g.lifePrevalence, g.creaturePrevalence, g.allowGiantKaltorGeneration, g.difficultyLevel, g.aggressionLevel, g.spawnNewEmpires]).toEqual([1000, 1.0, true, 1.0, 1.0, true]);
    }, 120000);
});

describe('createGame with wizard options', () => {
    it('difficulty sets Galaxy.DifficultyLevel and the empire difficulty factors (Galaxy.cs 1417 SetEmpireDifficultyFactors)', () => {
        const game = createGame({ ...tickGameOptions(gameData), difficultyLevel: 2.0, allowTechTrading: false, spawnNewEmpires: false, destroyedPiratesDoNotRespawn: true });
        const g = game.galaxy;
        expect(g.difficultyLevel).toBe(2.0);
        expect(g.allowTechTrading).toBe(false);
        expect(g.spawnNewEmpires).toBe(false);
        expect(g.destroyedPiratesDoNotRespawn).toBe(true);
        const p = game.playerEmpire;
        expect(p.difficultyLevel).toBeCloseTo(2.0 + p.difficultyLevelModifier, 12);
        expect(p.difficultyFactors!.researchRate).toBeCloseTo(1 / p.difficultyLevel, 12);
        const ai = g.empires.find((e) => e !== p)!;
        expect(ai.difficultyLevel).toBeCloseTo(1.0 + (1.0 - Math.sqrt(2.0)) + ai.difficultyLevelModifier, 12);
    }, 120000);

    it('the Custom Pirate playstyle creates a pirate player empire with the chosen playstyle (Start.2.cs 567-729)', () => {
        const o = start({ empireType: 'CustomPirate', piratePlayStyleIndex: 2, starCountIndex: 1, dimensionIndex: 1, otherEmpires: { autogenerate: true, empireCount: 3, manual: [] } });
        const c = toCreateGameOptions(o, gameData, NAMES);
        expect(c.player.playAsPirate).toBe(true);
        expect(c.player.piratePlayStyle).toBe(PiratePlayStyle.Mercenary);
        // Start.cs 3776 method_45: no Return of the Shakturi for a pirate.
        expect(c.victoryConditions!.enableStoryEvents).toBe(false);
        const game = createGame(c);
        const p = game.playerEmpire;
        expect(game.galaxy.playerEmpire).toBe(p);
        expect(p.pirateEmpireBaseHabitat).not.toBeNull();
        expect(game.galaxy.pirateEmpires).toContain(p);
        expect(game.galaxy.empires).not.toContain(p);
        expect(p.piratePlayStyle).toBe(PiratePlayStyle.Mercenary);
        expect(game.galaxy.storyReturnOfTheShakturiEnabled).toBe(false);
    }, 120000);

    it('the Custom Pirate playstyle raises a PreWarp tech level to Normal (Start.cs nVkoJxpyvO)', () => {
        const o = start({ empireTechLevelIndex: 0 });
        applyEmpireTypeChoice(o, 'CustomPirate');
        expect(o.empireTechLevelIndex).toBe(1);
    });
});

describe('Jump Start playstyles (Start.cs 5613 btnJumpStartTheGalaxyNext_Click)', () => {
    it('Classic Era / Return of the Shakturi / Legends: Starting galaxy, MaximumEmpireAmount AI empires, preset galaxy values', () => {
        for (const [type, shakturi, disasters, raceEvents] of [['ClassicEra', false, false, false], ['ReturnOfTheShakturi', true, false, false], ['Legends', true, true, true]] as const) {
            const c = toCreateGameOptions(start({ empireType: type, starCountIndex: 1, difficultyIndex: 3 }), gameData, NAMES);
            expect(c.galaxyAge).toBe(1);
            expect(c.aiEmpires.length).toBe(c.maximumEmpireAmount);
            expect(c.maximumEmpireAmount).toBe(15);
            expect([c.lifePrevalence, c.creaturePrevalence, c.aggressionLevel, c.piratePrevalence, c.pirateProximity, c.colonyPrevalence]).toEqual([400, 0.6, 1.1, 0.4, 1, 0.65]);
            expect(c.difficultyLevel).toBe(1.6);
            expect(c.storyDistantWorldsEnabled).toBe(true);
            const vc = c.victoryConditions!;
            expect([vc.enableStoryEvents, vc.enableDisasterEvents, vc.enableRaceSpecificEvents, vc.enableRaceSpecificVictoryConditions, vc.enableStoryEventsShadows]).toEqual([shakturi, disasters, raceEvents, raceEvents, false]);
            expect([vc.territory, vc.population, vc.economy, vc.victoryThresholdPercentage]).toEqual([true, true, true, 0.8]);
            expect(c.player.techLevel).toBe(0.5);
            expect(c.player.age).toBe(1);
            expect(c.ageOfShadows).toBe(false);
            expect(c.player.playAsPirate).toBeUndefined();
        }
    });

    it('Shadows: PreWarp galaxy, Shadows events, more pirates and life; the standard empire starts PreWarp, the pirate at Normal tech', () => {
        const std = toCreateGameOptions(start({ empireType: 'ShadowsStandard' }), gameData, NAMES);
        const pir = toCreateGameOptions(start({ empireType: 'ShadowsPirate', piratePlayStyleIndex: 3 }), gameData, NAMES);
        for (const c of [std, pir]) {
            expect(c.galaxyAge).toBe(0);
            expect(c.ageOfShadows).toBe(true);
            expect([c.lifePrevalence, c.aggressionLevel, c.piratePrevalence, c.colonyPrevalence]).toEqual([700, 1.3, 0.7, 0.82]);
            expect(c.victoryConditions!.enableStoryEventsShadows).toBe(true);
            expect(c.storyDistantWorldsEnabled).toBe(false);
            expect(c.player.age).toBe(0);
        }
        expect(std.pirateProximity).toBe(0);
        expect(std.player.techLevel).toBe(0.0);
        expect(std.victoryConditions!.enableStoryEvents).toBe(true);
        expect(pir.pirateProximity).toBe(1);
        expect(pir.player.techLevel).toBe(0.5);
        expect(pir.player.playAsPirate).toBe(true);
        expect(pir.player.piratePlayStyle).toBe(PiratePlayStyle.Smuggler);
        expect(pir.victoryConditions!.enableStoryEvents).toBe(false);
    });
});

describe('DestroyedPiratesDoNotRespawn (Galaxy.9.cs 23-30)', () => {
    function respawned(flag: boolean, nowMs: number): number {
        const game = cachedTickGame(gameData);
        const g = game.galaxy;
        expect(g.pirateEmpires.length).toBeGreaterThan(0);
        g.destroyedPiratesDoNotRespawn = flag;
        g.nowMs = nowMs;
        g.pirateEmpires.length = 0; // every faction destroyed
        generateNewPirateEmpires(g, { independentColonies: g.independentColonies, startingAge: g.startingAge, difficultyLevel: g.difficultyLevel }, { piratePrevalence: g.piratePrevalence, maximumEmpireAmount: g.maximumEmpireAmount, pirateProximity: g.pirateProximity });
        return g.pirateEmpires.length;
    }

    it('replaces destroyed factions by default', () => {
        expect(respawned(false, 600000)).toBeGreaterThan(0);
    }, 120000);

    it('keeps the current count once more than 300000 ms have passed', () => {
        expect(respawned(true, 600000)).toBe(0);
    }, 120000);

    it('still generates factions during the first 300000 ms', () => {
        expect(respawned(true, 300000)).toBeGreaterThan(0);
    }, 120000);
});

describe('Start.2.cs method_104: aggressive races among the four largest auto-generated starts', () => {
    it('swaps later aggressive starts into the top four (2 at aggression >= 1.1), both ending with the aggressive start\'s age', () => {
        const playable = gameData.races.filter((r) => r.playable);
        const aggressive = playable.filter((r) => r.aggression >= 115 && r.intelligence >= 90);
        const calm = playable.filter((r) => !aggressive.includes(r));
        expect(aggressive.length).toBeGreaterThanOrEqual(2);
        const mk = (race: (typeof playable)[number], age: number): ResolvedStart => ({ opts: { race: race.name, homeSystemFavourability: 'Normal', age, techLevel: 0.5 }, resolvedRace: race, projectedColonyAmount: 0 });
        const run = (level: number): ResolvedStart[] => {
            const list = [mk(calm[0], 3), mk(calm[1], 3), mk(calm[2], 3), mk(calm[3], 3), mk(aggressive[0], 1), mk(aggressive[1], 1), mk(calm[4], 1), mk(calm[5], 1)];
            ensureAggressiveAiRaces(list, playable, level, '', new Random(1));
            return list;
        };
        const ages = (l: ResolvedStart[]) => l.map((e) => e.opts.age).sort();
        const aggressiveAges = (l: ResolvedStart[]) => l.filter((e) => aggressive.includes(e.resolvedRace!)).map((e) => e.opts.age);
        // Aggression 1.1: num = 2 → two swaps; each displaced age-3 start takes the aggressive start's age 1 (C# quirk).
        const two = run(1.1);
        expect(ages(two)).toEqual([1, 1, 1, 1, 1, 1, 3, 3]);
        expect(aggressiveAges(two)).toEqual([1, 1]);
        // Below 1.1: num = 1 → one swap.
        expect(ages(run(0.9))).toEqual([1, 1, 1, 1, 1, 3, 3, 3]);
    });
});
