// Black holes, super novae and gas clouds in the Main View — ports of what DW:U 1.9.5 draws for them at each zoom
// factor f (= 1 / Camera.zoom):
//
// Black hole
//   - f < 500, system pass (MainView.1.cs method_76 649-722): star_blackhole_0 (texture2D_12[0]) drawn three times,
//     centred, at 1.0 / 0.44 / 0.2 x the star's drawn size (max(4, Diameter / f) px), each rotated by double_4 / 5.3,
//     double_4 / 2.3 and double_4 (double_4 += game seconds * 0.4) and tinted by one of four palettes picked by
//     HabitatIndex % 4; then the 100 BlkHole-* accretion frames (texture2D_13 = bitmap_200: each frame's 10 % border
//     cropped, scaled to 100 x 100, Main.Part13.cs LoadStars 1144-1162) at 0.08 x, 15 fps (method_117), untinted.
//   - f > 150, galaxy pass (MainView.2.cs method_250 5337-5374, 5476-5490): the map-star picture
//     bitmap_196[MapPictureRef] in a square of 2 * val3 px, val3 = max(MaxSolarSystemSize, TSV radius) / f * 2, at
//     least 5 and, below f 5100, clamped to 11..17. It is on spriteBatch_1, drawn over everything of spriteBatch_0.
//   Nothing spawns there and nothing else is drawn: the "Pull" (ShipPull) and "Event Horizon" (ShipDamage) galaxy
//   locations SetupSun adds (Galaxy.5.cs 1329-1352) are sim effects with no Main View art.
//
// Super nova
//   - f > 150, galaxy pass (MainView.2.cs 5359-5362, 5430-5434, 5449-5458, 5491-5501): the nova picture
//     bitmap_206[NovaImageIndexMajor] in a square of max(8, (int)(val4 * 1.3)) px, val4 = (int)(NovaProgression * 2 / f)
//     — world-linear, 2.6 x NovaProgression across (1.3 x the SuperNova location's diameter).
//   - f < 150, system pass: the star itself is not drawn (MainView.1.cs 730 `Type != SuperNova`); instead, while the
//     view centre is within half the view diagonal of a SuperNova galaxy location (DetermineGalaxyLocationsInRangeAtPoint,
//     MainView.1.cs 94-139), the whole view is filled with the pulsing method_29 colour (MainView.cs 1835-1852),
//     darkened by zoom, opaque, over the backdrop and under every system / ship. The location's ShieldReduction effect
//     on ships has no art.
//
// Gas cloud (a SystemInfo whose SystemStar is a GasCloud habitat; GenerateGasCloud places it inside a NebulaCloud
// location, Galaxy.4.cs 2834-2844)
//   - f > 150, galaxy pass (MainView.2.cs 5390-5394): the "+" cross — galaxyMarkers.ts.
//   - f < 500, system pass (MainView.1.cs 724-727 DrawGasCloudToMainXna, MainView.2.cs 2072-2099): bitmap_2, one
//     cloud generated by nebulaCloudGenerator_1.GenerateNebulaBackdrop(HabitatIndex, 255, colour scheme 20 + method_135
//     by type, min(100, Diameter), transparent, isGasCloud) (MainView.1.cs method_135 4507-4540), stretched over
//     Diameter x Diameter * h / w world units centred on the cloud (method_141), untinted. Magnified, the visible part
//     is re-rendered by method_146 (MainView.2.cs 20-103): the region of the bitmap under the view, inflated 2x, scaled
//     up min(10, 400 / width) times (at most 2000 px), with its alpha multiplied by (fBm + 1) / 2 of a CFractal
//     (seed HabitatIndex, H 0.35, lacunarity 2.6, 6 octaves) sampled at 10 / bitmap width per bitmap pixel
//     (SectorCloudGenerator.FbmImageTransparent); it is regenerated when the view leaves 1.2x of the last region.
//   No radiation field is drawn (MainView has no use of the Solar / Microwave / Xray radiation values).
//
// Render-only: nothing here touches sim state or the sim's random streams.

import { BufferImageSource, Container, Sprite, Texture, Rectangle } from 'pixi.js';
import { HabitatType, type Habitat } from '../sim/types';
import { CFractal } from './fbmNoise';
import { textureFromRgbaPixels, makeTextureCanvas, textureFromCanvas } from './textureCanvas';
import { useMinifyingFilter } from './assets';

const IMG = '/assets/dwu/images/environment';

// --- black hole ---------------------------------------------------------------------------------------------------

/** stars/star_blackhole_0.png (bitmap_199[0] → texture2D_12[0]). */
export const BLACK_HOLE_LAYER_URL = `${IMG}/stars/star_blackhole_0.png`;

/** stars/blackhole/BlkHole-0001 … 0100.png (bitmap_200, Main.Part13.cs 1144-1162: fixed names, 1-based). */
export function blackHoleFrameUrls(): string[] {
    const urls: string[] = [];
    for (let i = 1; i <= 100; i++) urls.push(`${IMG}/stars/blackhole/BlkHole-${String(i).padStart(4, '0')}.png`);
    return urls;
}

/** MainView.1.cs 657-680: the three layer tints [color_3 (inner), color_4 (middle), color_5 (outer)] by HabitatIndex % 4. */
export function blackHoleTints(habitatIndex: number): [number, number, number] {
    switch (((habitatIndex % 4) + 4) % 4) {
        case 0:
            return [0x0000d8, 0x00008a, 0x000070];
        case 1:
            return [0x54368a, 0x381e54, 0x30143c];
        case 2:
            return [0x362054, 0x26183c, 0x201430];
        default:
            return [0x541e60, 0x3e1448, 0x381040];
    }
}

/** One layer of the system-zoom black hole: size as a fraction of the drawn star, rotation = double_4 / divisor. */
export interface BlackHoleLayer {
    scale: number;
    divisor: number;
    /** Index into blackHoleTints' result. */
    tint: 0 | 1 | 2;
}

/** MainView.1.cs 690-716, in draw order (outer first). */
export const BLACK_HOLE_LAYERS: readonly BlackHoleLayer[] = [
    { scale: 1.0, divisor: 5.3, tint: 2 },
    { scale: 0.44, divisor: 2.3, tint: 1 },
    { scale: 0.2, divisor: 1, tint: 0 },
];
/** MainView.1.cs 717-721: the accretion animation's size factor and frame rate. */
export const BLACK_HOLE_FRAME_SCALE = 0.08;
export const BLACK_HOLE_FPS = 15;
/** MainView.1.cs 651: double_4 grows by 0.4 per second of Galaxy.CurrentDateTime. */
export const BLACK_HOLE_SPIN_PER_SECOND = 0.4;
/** The system pass draws habitats only while f < 500 (MainView.1.cs 436). */
export const SYSTEM_PASS_MAX_FACTOR = 500;

/** double_4 at game time `gameMs` (the C# accumulates the same game-time deltas). */
export function blackHoleSpin(gameMs: number): number {
    return (gameMs / 1000) * BLACK_HOLE_SPIN_PER_SECOND;
}

/** (int)(drawn * factor): a layer's px size (MainView.1.cs 686-718). */
export function blackHoleLayerPx(drawnPx: number, scale: number): number {
    return Math.trunc(drawnPx * scale);
}

/**
 * The galaxy-pass black hole picture's side in px (MainView.2.cs 5337-5374, 5476-5486): val3 =
 * (int)(max(MaxSolarSystemSize, TSV radius) / f), (int)(val3 * 2.0), at least 5, clamped to 11..17 below f 5100;
 * the square is 2 * val3.
 */
export function blackHoleGalaxyPx(f: number, systemRadius: number): number {
    let val3 = Math.trunc(systemRadius / f);
    val3 = Math.trunc(val3 * 2.0);
    val3 = Math.max(5, val3);
    if (f < 5100) val3 = Math.min(17, Math.max(11, val3));
    return val3 * 2;
}

/** The C# system radius (MainView.2.cs 5235-5338): max(MaxSolarSystemSize, min(TSV, 1500000)^0.35 * 600). */
export function systemPassRadius(totalStrategicValue: number, maxSolarSystemSize: number): number {
    const tsv = Math.min(Math.max(0, totalStrategicValue), 1500000);
    return Math.max(maxSolarSystemSize, Math.pow(tsv, 0.35) * 600.0);
}

/**
 * The shared black-hole art: the layer texture and the 100 accretion frames, each cropped by 10 % of its width on
 * every side and scaled to 100 x 100 (method_24 + PrecacheScaledBitmap), packed into one 1000 x 1000 atlas (one GPU
 * texture instead of a hundred 360 px ones). Loaded on first use.
 */
export class BlackHoleArt {
    layer: Texture = Texture.EMPTY;
    frames: Texture[] = [];
    private loading: Promise<void> | null = null;

    constructor(
        private readonly loadTexture: (url: string) => Promise<Texture>,
        private readonly loadImage: (url: string) => Promise<ImageBitmap | null>,
    ) {}

    get ready(): boolean {
        return this.frames.length > 0;
    }

    load(): Promise<void> {
        if (this.loading !== null) return this.loading;
        this.loading = (async () => {
            const [layer, images] = await Promise.all([this.loadTexture(BLACK_HOLE_LAYER_URL), Promise.all(blackHoleFrameUrls().map((u) => this.loadImage(u)))]);
            this.layer = layer;
            const cell = 100;
            const { canvas, ctx } = makeTextureCanvas(cell * 10, cell * 10);
            ctx.imageSmoothingEnabled = true;
            ctx.imageSmoothingQuality = 'high';
            const present: number[] = [];
            images.forEach((img, i) => {
                if (img === null) return;
                const crop = Math.trunc(img.width * 0.1);
                ctx.drawImage(img, crop, crop, img.width - crop * 2, img.height - crop * 2, (i % 10) * cell, Math.trunc(i / 10) * cell, cell, cell);
                img.close();
                present.push(i);
            });
            if (present.length === 0) {
                this.frames = [Texture.EMPTY];
                return;
            }
            const atlas = textureFromCanvas(canvas, 'blackhole-frames');
            useMinifyingFilter(atlas);
            // A missing frame keeps the previous one (the C# would have thrown; a partial install should still animate).
            const frames: Texture[] = [];
            let last = present[0];
            for (let i = 0; i < 100; i++) {
                if (images[i] !== null) last = i;
                frames.push(new Texture({ source: atlas.source, frame: new Rectangle((last % 10) * cell, Math.trunc(last / 10) * cell, cell, cell) }));
            }
            this.frames = frames;
        })();
        return this.loading;
    }
}

/** The system-zoom black hole of one system: three tinted rotating layers and the accretion animation. */
export class BlackHoleView {
    readonly root = new Container();
    private readonly layers: Sprite[] = [];
    private readonly accretion = new Sprite(Texture.EMPTY);
    private readonly tints: [number, number, number];

    constructor(habitatIndex: number, private readonly art: BlackHoleArt) {
        this.tints = blackHoleTints(habitatIndex);
        for (const l of BLACK_HOLE_LAYERS) {
            const s = new Sprite(Texture.EMPTY);
            s.anchor.set(0.5);
            s.tint = this.tints[l.tint];
            this.layers.push(s);
            this.root.addChild(s);
        }
        this.accretion.anchor.set(0.5);
        this.root.addChild(this.accretion);
        this.root.visible = false;
    }

    /** Per frame: `drawnPx` = max(4, Diameter / f), `gameMs` = the render-interpolated game clock. */
    update(show: boolean, drawnPx: number, z: number, gameMs: number, coronaFrameIndex: (nowMs: number, n: number, fps: number) => number): void {
        if (!show) {
            this.root.visible = false;
            return;
        }
        if (!this.art.ready) {
            void this.art.load();
            this.root.visible = false;
            return;
        }
        this.root.visible = true;
        const spin = blackHoleSpin(gameMs);
        for (let i = 0; i < BLACK_HOLE_LAYERS.length; i++) {
            const l = BLACK_HOLE_LAYERS[i];
            const s = this.layers[i];
            if (s.texture !== this.art.layer) s.texture = this.art.layer;
            const px = blackHoleLayerPx(drawnPx, l.scale);
            s.visible = px > 0 && s.texture.width > 1;
            if (!s.visible) continue;
            s.scale.set(px / (s.texture.width * z));
            s.rotation = spin / l.divisor;
        }
        const fpx = blackHoleLayerPx(drawnPx, BLACK_HOLE_FRAME_SCALE);
        this.accretion.visible = fpx > 0;
        if (this.accretion.visible) {
            this.accretion.texture = this.art.frames[coronaFrameIndex(gameMs, this.art.frames.length, BLACK_HOLE_FPS)] ?? this.art.frames[0];
            this.accretion.scale.set(fpx / (this.accretion.texture.width * z));
        }
    }
}

// --- super nova ---------------------------------------------------------------------------------------------------

/** f below which the system pass draws (and the location fill shows): MainView.1.cs 94 / method_60(SuperNova). */
export const NOVA_FILL_MAX_FACTOR = 150;

/** The galaxy-pass nova picture's side in px: max(8, (int)((int)(NovaProgression * 2 / f) * 1.3)) (MainView.2.cs). */
export function supernovaGalaxyPx(novaProgression: number, f: number): number {
    const val4 = Math.trunc((novaProgression * 2.0) / f);
    return Math.max(8, Math.trunc(val4 * 1.3));
}

/**
 * Above f 500 the galaxy pass draws with BlendState.AlphaBlend (MainView.cs 1509-1512), a premultiplied blend, while
 * the nova texture texture2D_20 = BitmapToTexture (a PNG round trip through Texture2D.FromStream, which keeps straight
 * alpha) — so the picture's straight colour is added: dst * (1 - a) + rgb. From f 500 in (NonPremultiplied) it blends
 * normally. This loads the picture with its straight samples uploaded as if premultiplied, which gives that blend.
 *
 * The samples are the ones bitmap_206 holds, not the PNG's: LoadSuperNovae (Main.Part13.cs 1203-1214) copies each
 * picture through method_21 (983) into a Format32bppPArgb bitmap, so every sample is premultiplied and back. A fully
 * transparent pixel loses its colour that way (11 of the 20 stock NovaCloud PNGs store white there, which the additive
 * blend would draw as a white square), and faint pixels are quantised the same way a premultiplied canvas does it.
 */
export const NOVA_ALPHA_BLEND_MIN_FACTOR = 500;

/** method_21's Format32bppPArgb copy on straight RGBA, in place: premultiply to 8 bits and back; alpha 0 -> 0,0,0,0. */
export function pargbRoundTrip(rgba: Uint8ClampedArray | Uint8Array): void {
    for (let i = 0; i < rgba.length; i += 4) {
        const a = rgba[i + 3];
        if (a === 255) continue;
        for (let c = 0; c < 3; c++) {
            if (a === 0) {
                rgba[i + c] = 0;
                continue;
            }
            const p = Math.round((rgba[i + c] * a) / 255);
            rgba[i + c] = Math.min(255, Math.round((p * 255) / a));
        }
    }
}

export async function loadStraightAsPremultiplied(url: string): Promise<Texture | null> {
    try {
        const r = await fetch(url);
        if (!r.ok) return null;
        const bmp = await createImageBitmap(await r.blob(), { premultiplyAlpha: 'none', colorSpaceConversion: 'none' });
        // A software canvas stores premultiplied pixels; reading them back gives straight samples (alpha 0 -> black),
        // and pargbRoundTrip makes the method_21 result explicit whatever the browser's canvas storage.
        const { ctx } = makeTextureCanvas(bmp.width, bmp.height);
        ctx.drawImage(bmp, 0, 0);
        bmp.close();
        const data = ctx.getImageData(0, 0, ctx.canvas.width, ctx.canvas.height).data;
        pargbRoundTrip(data);
        const source = new BufferImageSource({ resource: new Uint8Array(data.buffer), width: ctx.canvas.width, height: ctx.canvas.height, alphaMode: 'premultiplied-alpha' });
        const tex = new Texture({ source, label: `${url} (xna alpha blend)` });
        useMinifyingFilter(tex);
        return tex;
    } catch {
        return null;
    }
}

export interface Argb {
    a: number;
    r: number;
    g: number;
    b: number;
}

/**
 * Port of MainView.cs method_29: (120,255,96,64) ↔ (160,232,160,0) on a 2 s triangle wave of the UTC clock. The C#
 * subtracts (byte)(delta * t) in wrapping byte arithmetic, i.e. channel + trunc((target - channel) * t).
 */
export function supernovaPulseColour(utcMs: number): Argb {
    const second = Math.floor(utcMs / 1000);
    let ms = Math.floor(utcMs) - second * 1000;
    if (second % 2 === 1) ms += 1000;
    const t = ms <= 1000 ? Math.abs(1000 - ms) / 1000 : (ms - 1000) / 1000;
    const lerp = (a: number, b: number): number => (a - (Math.trunc((a - b) * t) & 0xff)) & 0xff;
    return { a: lerp(120, 160), r: lerp(255, 232), g: lerp(96, 160), b: lerp(64, 0) };
}

/** MainView.1.cs 125-132: the fill colour's channels scaled by A / 255 * the zoom ramp, drawn opaque. */
export function supernovaFillColour(f: number, utcMs: number): number {
    const c = supernovaPulseColour(utcMs);
    const ramp = f < 75.0 ? (f + 30.0) / 167.0 + 0.35 : (150.0 - f) / 167.0 + 0.35;
    const k = (c.a / 255.0) * ramp;
    const r = Math.trunc(c.r * k) & 0xff;
    const g = Math.trunc(c.g * k) & 0xff;
    const b = Math.trunc(c.b * k) & 0xff;
    return (r << 16) | (g << 8) | b;
}

// --- gas cloud ----------------------------------------------------------------------------------------------------

/** MainView.1.cs method_135: the gas cloud's colour scheme offset (the generator gets 20 + this). */
export function gasCloudColorScheme(type: HabitatType): number {
    switch (type) {
        case HabitatType.Hydrogen:
            return 6;
        case HabitatType.Helium:
            return 0;
        case HabitatType.Argon:
            return 2;
        case HabitatType.Ammonia:
            return 4;
        case HabitatType.CarbonDioxide:
            return 7;
        case HabitatType.Oxygen:
            return 1;
        case HabitatType.NitrogenOxygen:
            return 3;
        case HabitatType.Chlorine:
            return 5;
        default:
            return -1;
    }
}

/** method_135: GenerateNebulaBackdrop's minimum / maximum size, min(100, Diameter). */
export function gasCloudBitmapSize(diameter: number): number {
    return Math.min(100, Math.trunc(diameter));
}

export interface RgbaImage {
    image: Uint8ClampedArray;
    width: number;
    height: number;
}

/** A source rectangle in bitmap pixels. */
export interface PxRect {
    x: number;
    y: number;
    w: number;
    h: number;
}

/** method_146 1st half: the up-scale for a source region `srcW` px wide, min(10, 400 / srcW), at least 1. */
export function gasCloudDetailScale(srcW: number): number {
    if (srcW <= 0) return 10;
    const val = Math.min(10.0, 400 / srcW);
    return val > 1.0 ? val : 1.0;
}

/**
 * MainView.1.cs method_136 / 137-143: the visible part of the cloud in bitmap px (the screen ∩ the cloud rect), or
 * null when the cloud is off screen. `view` is the camera's world rect.
 */
export function gasCloudVisibleRect(cloud: Pick<Habitat, 'xpos' | 'ypos' | 'diameter'>, bmpW: number, bmpH: number, view: PxRect): PxRect | null {
    const w = cloud.diameter;
    const h = (cloud.diameter * bmpH) / bmpW;
    const left = cloud.xpos - w / 2;
    const top = cloud.ypos - h / 2;
    const x0 = Math.max(left, view.x);
    const y0 = Math.max(top, view.y);
    const x1 = Math.min(left + w, view.x + view.w);
    const y1 = Math.min(top + h, view.y + view.h);
    if (x1 <= x0 || y1 <= y0) return null;
    const s = bmpW / w;
    return { x: (x0 - left) * s, y: (y0 - top) * s, w: (x1 - x0) * s, h: (y1 - y0) * s };
}

/** method_123: inflate a rect by `factor` about its centre. */
export function inflateRect(r: PxRect, factor: number): PxRect {
    const w = r.w * factor;
    const h = r.h * factor;
    return { x: r.x - (w - r.w) / 2, y: r.y - (h - r.h) / 2, w, h };
}

/** method_143: clip a rect to the bitmap. */
export function clipRect(r: PxRect, bmpW: number, bmpH: number): PxRect {
    let { x, y, w, h } = r;
    if (x + w >= bmpW) w -= x + w - bmpW;
    if (y + h >= bmpH) h -= y + h - bmpH;
    if (x < 0) {
        w += x;
        x = 0;
    }
    if (y < 0) {
        h += y;
        y = 0;
    }
    return { x, y, w, h };
}

export function rectContains(outer: PxRect, inner: PxRect): boolean {
    return inner.x >= outer.x && inner.y >= outer.y && inner.x + inner.w <= outer.x + outer.w && inner.y + inner.h <= outer.y + outer.h;
}

/**
 * Port of MainView.2.cs method_146 (bool_13 transparent, float_0 0.1, float_1 10) for `src` (bitmap px) of `base`:
 * the region scaled by `scale` (output at most 2000 px a side; the C# draws it with HighQualityBicubic, here bilinear
 * on premultiplied samples), then SectorCloudGenerator.FbmImageTransparent — every pixel with alpha keeps
 * (int)(A * (fBm(u, v, 6) + 1) / 2), u / v starting at src.x / src.y * 10 / base.width and stepping
 * 10 / (base.width * scale) per output pixel. Rows [row0, row1) of the output only (the caller time-slices).
 */
export function renderGasCloudDetailRows(base: RgbaImage, src: PxRect, scale: number, fractal: CFractal, out: Uint8ClampedArray, outW: number, row0: number, row1: number): void {
    const bw = base.width;
    const bh = base.height;
    const img = base.image;
    const startU = (src.x * 10) / bw;
    const startV = (src.y * 10) / bw;
    const skip = 10 / (bw * scale);
    for (let y = row0; y < row1; y++) {
        const sy = src.y + (y + 0.5) / scale - 0.5;
        const y0 = Math.max(0, Math.min(bh - 1, Math.floor(sy)));
        const y1 = Math.min(bh - 1, y0 + 1);
        const ty = Math.max(0, Math.min(1, sy - Math.floor(sy)));
        const v = startV + y * skip;
        let o = y * outW * 4;
        for (let x = 0; x < outW; x++, o += 4) {
            const sx = src.x + (x + 0.5) / scale - 0.5;
            const x0 = Math.max(0, Math.min(bw - 1, Math.floor(sx)));
            const x1 = Math.min(bw - 1, x0 + 1);
            const tx = Math.max(0, Math.min(1, sx - Math.floor(sx)));
            const i00 = (y0 * bw + x0) * 4;
            const i10 = (y0 * bw + x1) * 4;
            const i01 = (y1 * bw + x0) * 4;
            const i11 = (y1 * bw + x1) * 4;
            const w00 = (1 - tx) * (1 - ty);
            const w10 = tx * (1 - ty);
            const w01 = (1 - tx) * ty;
            const w11 = tx * ty;
            const a00 = img[i00 + 3] * w00;
            const a10 = img[i10 + 3] * w10;
            const a01 = img[i01 + 3] * w01;
            const a11 = img[i11 + 3] * w11;
            const a = a00 + a10 + a01 + a11;
            if (a < 0.5) {
                out[o + 3] = 0;
                continue;
            }
            const r = (img[i00] * a00 + img[i10] * a10 + img[i01] * a01 + img[i11] * a11) / a;
            const g = (img[i00 + 1] * a00 + img[i10 + 1] * a10 + img[i01 + 1] * a01 + img[i11 + 1] * a11) / a;
            const b = (img[i00 + 2] * a00 + img[i10 + 2] * a10 + img[i01 + 2] * a01 + img[i11 + 2] * a11) / a;
            const n = fractal.fBm(startU + x * skip, v, 6);
            out[o] = r;
            out[o + 1] = g;
            out[o + 2] = b;
            out[o + 3] = Math.trunc(Math.trunc(a) * ((n + 1) / 2));
        }
    }
}

/** method_146's output size for `src` at `scale` (each side at least 1, at most 2000). */
export function gasCloudDetailSize(src: PxRect, scale: number): { w: number; h: number } {
    return { w: Math.min(2000, Math.max(1, Math.trunc(src.w * scale))), h: Math.min(2000, Math.max(1, Math.trunc(src.h * scale))) };
}

/** A time-sliced method_146 render: call step() until it returns a texture. */
export class GasCloudDetailJob {
    readonly size: { w: number; h: number };
    private readonly out: Uint8ClampedArray;
    private row = 0;
    constructor(
        private readonly base: RgbaImage,
        readonly src: PxRect,
        readonly scale: number,
        private readonly fractal: CFractal,
    ) {
        this.size = gasCloudDetailSize(src, scale);
        this.out = new Uint8ClampedArray(this.size.w * this.size.h * 4);
    }
    get done(): boolean {
        return this.row >= this.size.h;
    }
    /** Render rows until `budgetMs` is spent; the finished texture once the last row is done, else null. */
    step(budgetMs: number, now: () => number = () => performance.now()): Texture | null {
        const t0 = now();
        while (this.row < this.size.h) {
            const next = Math.min(this.size.h, this.row + 8);
            renderGasCloudDetailRows(this.base, this.src, this.scale, this.fractal, this.out, this.size.w, this.row, next);
            this.row = next;
            if (now() - t0 >= budgetMs) break;
        }
        if (this.row < this.size.h) return null;
        const tex = textureFromRgbaPixels(this.out, this.size.w, this.size.h, false, 'gascloud-detail');
        useMinifyingFilter(tex);
        return tex;
    }
}

/** The pixel stats a test or a screenshot report wants of a generated cloud. */
export function opaqueShare(img: RgbaImage): number {
    let n = 0;
    for (let i = 3; i < img.image.length; i += 4) if (img.image[i] > 0) n++;
    return n / (img.width * img.height);
}

/** Per-frame work allowance shared by every gas cloud (reset by the Main View each frame). */
export interface GasCloudFrameBudget {
    /** Milliseconds of time-sliced method_146 rendering left this frame. */
    ms: number;
    /** Whole-bitmap generations (GenerateNebulaBackdrop, not sliceable) left this frame. */
    generations: number;
}

/** Generated gas clouds (base bitmap + whole-cloud texture) kept at once; older ones are rebuilt on demand. */
export const GAS_CLOUD_CACHE_LIMIT = 16;
/** A magnified patch is rendered once the C# scale exceeds the whole-cloud texture's by this factor. */
const PATCH_SCALE_STEP = 1.5;

/**
 * One gas cloud at system zoom (f < 500): bitmap_2 rendered whole at its own method_146 scale (what the C# shows
 * while the whole cloud is in view), and — magnified further — a patch of the visible region at the C# scale.
 */
export class GasCloudView {
    readonly root = new Container();
    private readonly full = new Sprite(Texture.EMPTY);
    private readonly patch = new Sprite(Texture.EMPTY);
    private base: RgbaImage | null = null;
    private fractal: CFractal | null = null;
    private fullJob: GasCloudDetailJob | null = null;
    private patchJob: GasCloudDetailJob | null = null;
    private patchSrc: PxRect | null = null;
    private patchScale = 0;
    /** Most-recently-used order of clouds holding generated art (shared by all views). */
    private static readonly lru: GasCloudView[] = [];
    /** The one view holding a magnified patch. */
    private static patchOwner: GasCloudView | null = null;

    constructor(
        readonly cloud: Habitat,
        private readonly generate: (cloud: Habitat) => RgbaImage,
    ) {
        this.full.anchor.set(0.5);
        this.root.addChild(this.full, this.patch);
        this.root.position.set(cloud.xpos, cloud.ypos);
        this.root.visible = false;
        this.full.visible = false;
        this.patch.visible = false;
    }

    /** Whether the generated art is in memory (tests / diagnostics). */
    get hasArt(): boolean {
        return this.base !== null;
    }

    /** Whether the cloud is drawn at zoom factor `f` over the world rect `view` (f < 500 and on screen). */
    inView(f: number, view: PxRect): boolean {
        const d = this.cloud.diameter;
        return (
            f < SYSTEM_PASS_MAX_FACTOR &&
            this.cloud.xpos + d > view.x &&
            this.cloud.xpos - d < view.x + view.w &&
            this.cloud.ypos + d > view.y &&
            this.cloud.ypos - d < view.y + view.h
        );
    }

    /** `view` = the camera's world rect; `f` the zoom factor. */
    update(f: number, view: PxRect, budget: GasCloudFrameBudget): void {
        const d = this.cloud.diameter;
        if (!this.inView(f, view)) {
            this.root.visible = false;
            return;
        }
        if (this.base === null) {
            if (budget.generations <= 0) {
                this.root.visible = false;
                return;
            }
            budget.generations--;
            this.base = this.generate(this.cloud);
            // MainView.1.cs 4538: new SectorCloudGenerator(HabitatIndex, 4) — its CFractal(HabitatIndex, 0.35, 2.6).
            this.fractal = new CFractal(this.cloud.habitatIndex, 0.35, 2.6);
            this.touch();
        }
        const base = this.base;
        const fractal = this.fractal!;
        this.root.visible = true;
        const s = d / base.width; // world units per bitmap pixel
        // The whole cloud at the C# scale for a source as wide as the bitmap (min(10, 400 / width)).
        if (this.full.texture === Texture.EMPTY) {
            this.fullJob ??= new GasCloudDetailJob(base, { x: 0, y: 0, w: base.width, h: base.height }, gasCloudDetailScale(base.width), fractal);
            if (budget.ms > 0) {
                const t0 = performance.now();
                const tex = this.fullJob.step(budget.ms);
                budget.ms -= performance.now() - t0;
                if (tex !== null) {
                    this.full.texture = tex;
                    this.fullJob = null;
                }
            }
        }
        const fullReady = this.full.texture !== Texture.EMPTY;
        if (fullReady) this.full.scale.set(d / this.full.texture.width, (base.height * s) / this.full.texture.height);
        // method_136: the region under the view, inflated 2x and clipped, re-rendered at min(10, 400 / width).
        const visible = gasCloudVisibleRect(this.cloud, base.width, base.height, view);
        let patchShown = false;
        if (visible !== null && fullReady) {
            const region = clipRect(inflateRect(visible, 2), base.width, base.height);
            const scale = gasCloudDetailScale(region.w);
            if (scale > gasCloudDetailScale(base.width) * PATCH_SCALE_STEP) {
                // Regenerate when the view leaves the last region (1.2x guard, method_136 4570) or the zoom moved on.
                const guard = clipRect(inflateRect(inflateRect(visible, 1.2), 0.99), base.width, base.height);
                const current = this.patchSrc !== null && rectContains(this.patchSrc, guard) && Math.abs(this.patchScale / scale - 1) < 0.25;
                if (!current && (this.patchJob === null || !rectContains(this.patchJob.src, guard) || Math.abs(this.patchJob.scale / scale - 1) >= 0.25)) {
                    this.patchJob = new GasCloudDetailJob(base, region, scale, fractal);
                }
                if (this.patchJob !== null && budget.ms > 0) {
                    const t0 = performance.now();
                    const tex = this.patchJob.step(budget.ms);
                    budget.ms -= performance.now() - t0;
                    if (tex !== null) {
                        this.setPatch(tex, this.patchJob.src, this.patchJob.scale);
                        this.patchJob = null;
                    }
                }
                patchShown = this.patchSrc !== null && rectContains(this.patchSrc, visible);
            } else {
                this.patchJob = null;
            }
        }
        if (patchShown) {
            const r = this.patchSrc!;
            const left = -d / 2;
            const top = -(base.height * s) / 2;
            this.patch.position.set(left + r.x * s, top + r.y * s);
            this.patch.scale.set((r.w * s) / this.patch.texture.width, (r.h * s) / this.patch.texture.height);
        }
        this.patch.visible = patchShown;
        this.full.visible = fullReady && !patchShown;
        if (patchShown || fullReady) this.touch();
    }

    private setPatch(tex: Texture, src: PxRect, scale: number): void {
        const owner = GasCloudView.patchOwner;
        if (owner !== null && owner !== this) owner.dropPatch();
        this.dropPatch();
        this.patch.texture = tex;
        this.patchSrc = src;
        this.patchScale = scale;
        GasCloudView.patchOwner = this;
    }

    private dropPatch(): void {
        if (this.patch.texture !== Texture.EMPTY) this.patch.texture.destroy(true);
        this.patch.texture = Texture.EMPTY;
        this.patch.visible = false;
        this.patchSrc = null;
        this.patchJob = null;
        if (GasCloudView.patchOwner === this) GasCloudView.patchOwner = null;
    }

    private touch(): void {
        const lru = GasCloudView.lru;
        const i = lru.indexOf(this);
        if (i === lru.length - 1 && i >= 0) return;
        if (i >= 0) lru.splice(i, 1);
        lru.push(this);
        while (lru.length > GAS_CLOUD_CACHE_LIMIT) lru.shift()!.release();
    }

    /** Free the generated art (it is regenerated, identically, the next time the cloud is in view). */
    release(): void {
        this.dropPatch();
        if (this.full.texture !== Texture.EMPTY) this.full.texture.destroy(true);
        this.full.texture = Texture.EMPTY;
        this.full.visible = false;
        this.base = null;
        this.fractal = null;
        this.fullJob = null;
        const i = GasCloudView.lru.indexOf(this);
        if (i >= 0) GasCloudView.lru.splice(i, 1);
    }
}

/**
 * The system-pass location fill (MainView.1.cs method_76 94-139) for super novae: below f 150, with a SuperNova galaxy
 * location within half the view diagonal * f of the view centre, the whole view is filled with supernovaFillColour —
 * opaque, so it hides the backdrop and the nebula art beneath it (the Main View puts it just under the systems).
 * TODO(port): the same fill's NebulaCloud colour (method_122: the galaxy nebula image bitmap_182's pixel x2, which the
 * port does not build) and the lightning flash (method_28's (192,224,192,224) frames; the thunder is
 * audio/mainViewSounds.ts) — MainView.1.cs method_76 94-139.
 */
export class NovaFill {
    readonly sprite = new Sprite(Texture.WHITE);
    constructor() {
        this.sprite.visible = false;
    }

    update(inNova: boolean, f: number, view: PxRect, utcMs: number): void {
        if (!inNova || f >= NOVA_FILL_MAX_FACTOR) {
            this.sprite.visible = false;
            return;
        }
        this.sprite.visible = true;
        this.sprite.tint = supernovaFillColour(f, utcMs);
        this.sprite.position.set(view.x, view.y);
        this.sprite.scale.set(view.w / this.sprite.texture.width, view.h / this.sprite.texture.height);
    }
}

/** MainView.cs 672 double_9 * f: the range (world units) the fill tests the SuperNova locations against. */
export function novaFillRange(viewWidthPx: number, viewHeightPx: number, f: number): number {
    return Math.sqrt(Math.pow(viewWidthPx / 2, 2) + Math.pow(viewHeightPx / 2, 2)) * f;
}
