// Port of the Galaxy.2.cs ResolveDescription(enum) overloads that empire / event message texts use: each maps an enum
// member to TextResolver.GetText(<GameText.txt tag>); members without a case fall back to string.Empty (switch
// statements) or SplitString(member.ToString()) (switch expressions with `_ => SplitString(...)`). The tables below are
// the C# cases verbatim (tag strings as in the C# source; every tag is in GameText.txt).
//
// Like the C#, the result is the resolved text (callers ToLower it or format it into another message). Without a loaded
// GameText table (headless tests without game data) the tag itself is returned.

import { getText, isTextLoaded } from './textResolver';
import { splitString } from './data/gameText';

export interface EnumText {
    fallback: 'empty' | 'split';
    tags: Readonly<Record<string, string>>;
}

/** Galaxy.2.cs 1518-1813 ResolveDescription(CharacterTraitType): member → GameText tag; other members → string.Empty. */
export const CHARACTER_TRAIT: EnumText = { fallback: 'empty', tags: {
    IntelligenceUninhibited: 'Character Trait Uninhibited',
    IntelligenceMeasured: 'Character Trait Measured',
    IntelligenceAddict: 'Character Trait Addict',
    IntelligenceSober: 'Character Trait Sober',
    IntelligenceCourageous: 'Character Trait Courageous',
    IntelligenceWeak: 'Character Trait Weak',
    IntelligenceTolerant: 'Character Trait Tolerant',
    IntelligenceXenophobic: 'Character Trait Xenophobic',
    IntelligenceEloquentSpeaker: 'Character Trait EloquentSpeaker',
    IntelligencePoorSpeaker: 'Character Trait PoorSpeaker',
    IntelligenceCorrupt: 'Character Trait Corrupt',
    IntelligenceLawful: 'Character Trait Lawful',
    Undefined: 'None',
    Addict: 'Character Trait Addict',
    BeanCounter: 'Character Trait BeanCounter',
    CarefulAttacker: 'Character Trait CarefulAttacker',
    Corrupt: 'Character Trait Corrupt',
    Courageous: 'Character Trait Courageous',
    Creative: 'Character Trait Creative',
    Demoralizing: 'Character Trait Demoralizing',
    Diplomat: 'Character Trait Diplomat',
    Disliked: 'Character Trait Disliked',
    Disorganized: 'Character Trait Disorganized',
    DoubleAgent: 'Character Trait DoubleAgent',
    Drunk: 'Character Trait Drunk',
    EloquentSpeaker: 'Character Trait EloquentSpeaker',
    Energetic: 'Character Trait Energetic',
    Engineer: 'Character Trait Engineer',
    Environmentalist: 'Character Trait Environmentalist',
    Expansionist: 'Character Trait Expansionist',
    Famous: 'Character Trait Famous',
    ForeignSpy: 'Character Trait ForeignSpy',
    FreeTrader: 'Character Trait FreeTrader',
    Generous: 'Character Trait Generous',
    GoodAdministrator: 'Character Trait GoodAdministrator',
    GoodGroundLogistician: 'Character Trait GoodGroundLogistician',
    GoodRecruiter: 'Character Trait GoodRecruiter',
    GoodSpaceLogistician: 'Character Trait GoodSpaceLogistician',
    GoodStrategist: 'Character Trait GoodStrategist',
    GoodTactician: 'Character Trait GoodTactician',
    HealthOriented: 'Character Trait HealthOriented',
    Industrialist: 'Character Trait Industrialist',
    InspiringPresence: 'Character Trait InspiringPresence',
    Isolationist: 'Character Trait Isolationist',
    LaborOriented: 'Character Trait LaborOriented',
    Lawful: 'Character Trait Lawful',
    LaxDiscipline: 'Character Trait LaxDiscipline',
    Lazy: 'Character Trait Lazy',
    Linguist: 'Character Trait Linguist',
    LocalDefenseTactics: 'Character Trait LocalDefenseTactics',
    Logical: 'Character Trait Logical',
    Luddite: 'Character Trait Luddite',
    Measured: 'Character Trait Measured',
    Methodical: 'Character Trait Methodical',
    NaturalGroundLeader: 'Character Trait NaturalGroundLeader',
    NaturalSpaceLeader: 'Character Trait NaturalSpaceLeader',
    NonTechnical: 'Character Trait NonTechnical',
    Obnoxious: 'Character Trait Obnoxious',
    Organized: 'Character Trait Organized',
    Pacifist: 'Character Trait Pacifist',
    Paranoid: 'Character Trait Paranoid',
    Patriot: 'Character Trait Patriot',
    PeaceThroughStrength: 'Character Trait PeaceThroughStrength',
    PlanetarySupport: 'Character Trait PlanetarySupport',
    PoorAdministrator: 'Character Trait PoorAdministrator',
    PoorGroundAttacker: 'Character Trait PoorGroundAttacker',
    PoorGroundDefender: 'Character Trait PoorGroundDefender',
    PoorGroundLogistician: 'Character Trait PoorGroundLogistician',
    PoorNavigator: 'Character Trait PoorNavigator',
    PoorRecruiter: 'Character Trait PoorRecruiter',
    PoorSpaceAttacker: 'Character Trait PoorSpaceAttacker',
    PoorSpaceDefender: 'Character Trait PoorSpaceDefender',
    PoorSpaceLogistician: 'Character Trait PoorSpaceLogistician',
    PoorSpeaker: 'Character Trait PoorSpeaker',
    PoorStrategist: 'Character Trait PoorStrategist',
    PoorTactician: 'Character Trait PoorTactician',
    Protectionist: 'Character Trait Protectionist',
    RecklessAttacker: 'Character Trait RecklessAttacker',
    SkilledNavigator: 'Character Trait SkilledNavigator',
    Sober: 'Character Trait Sober',
    Spiritual: 'Character Trait Spiritual',
    StrongGroundAttacker: 'Character Trait StrongGroundAttacker',
    StrongGroundDefender: 'Character Trait StrongGroundDefender',
    StrongSpaceAttacker: 'Character Trait StrongSpaceAttacker',
    StrongSpaceDefender: 'Character Trait StrongSpaceDefender',
    Technical: 'Character Trait Technical',
    Tolerant: 'Character Trait Tolerant',
    TongueTied: 'Character Trait TongueTied',
    ToughDiscipline: 'Character Trait ToughDiscipline',
    Trusting: 'Character Trait Trusting',
    UltraGenius: 'Character Trait UltraGenius',
    Uninhibited: 'Character Trait Uninhibited',
    Weak: 'Character Trait Weak',
    Xenophobic: 'Character Trait Xenophobic',
    Smuggler: 'Character Trait Smuggler',
    BountyHunter: 'Character Trait BountyHunter',
} };

/** Galaxy.2.cs 1815-1975 ResolveDescription(CharacterSkillType): member → GameText tag; other members → string.Empty. */
export const CHARACTER_SKILL: EnumText = { fallback: 'empty', tags: {
    Undefined: 'None',
    Assassination: 'Character Skill Assassination',
    CivilianBaseMaintenance: 'Character Skill CivilianBaseMaintenance',
    CivilianShipConstructionSpeed: 'Character Skill CivilianShipConstructionSpeed',
    CivilianShipMaintenance: 'Character Skill CivilianShipMaintenance',
    ColonyCorruption: 'Character Skill ColonyCorruption',
    ColonyHappiness: 'Character Skill ColonyHappiness',
    ColonyIncome: 'Character Skill ColonyIncome',
    ColonyShipConstructionSpeed: 'Character Skill ColonyShipConstructionSpeed',
    Concealment: 'Character Skill Concealment',
    CounterEspionage: 'Character Skill CounterEspionage',
    Countermeasures: 'Character Skill Countermeasures',
    DamageControl: 'Character Skill DamageControl',
    Diplomacy: 'Character Skill Diplomacy',
    Espionage: 'Character Skill Espionage',
    FacilityConstructionSpeed: 'Character Skill FacilityConstructionSpeed',
    Fighters: 'Character Skill Fighters',
    HyperjumpSpeed: 'Character Skill HyperjumpSpeed',
    MilitaryBaseMaintenance: 'Character Skill MilitaryBaseMaintenance',
    MilitaryShipConstructionSpeed: 'Character Skill MilitaryShipConstructionSpeed',
    MilitaryShipMaintenance: 'Character Skill MilitaryShipMaintenance',
    MiningRate: 'Character Skill MiningRate',
    PopulationGrowth: 'Character Skill PopulationGrowth',
    PsyOps: 'Character Skill PsyOps',
    RepairBonus: 'Character Skill RepairBonus',
    ResearchEnergy: 'Character Skill ResearchEnergy',
    ResearchHighTech: 'Character Skill ResearchHighTech',
    ResearchWeapons: 'Character Skill ResearchWeapons',
    Sabotage: 'Character Skill Sabotage',
    ShieldRechargeRate: 'Character Skill ShieldRechargeRate',
    ShipEnergyUsage: 'Character Skill ShipEnergyUsage',
    ShipManeuvering: 'Character Skill ShipManeuvering',
    Targeting: 'Character Skill Targeting',
    TourismIncome: 'Character Skill TourismIncome',
    TradeIncome: 'Character Skill TradeIncome',
    TroopExperienceGain: 'Character Skill TroopExperienceGain',
    TroopGroundAttack: 'Character Skill TroopGroundAttack',
    TroopGroundDefense: 'Character Skill TroopGroundDefense',
    TroopMaintenance: 'Character Skill TroopMaintenance',
    TroopRecoveryRate: 'Character Skill TroopRecoveryRate',
    TroopRecruitment: 'Character Skill TroopRecruitment',
    WarWeariness: 'Character Skill WarWeariness',
    WeaponsDamage: 'Character Skill WeaponsDamage',
    WeaponsRange: 'Character Skill WeaponsRange',
    TroopStrengthArmor: 'Character Skill TroopStrengthArmor',
    TroopStrengthInfantry: 'Character Skill TroopStrengthInfantry',
    TroopStrengthSpecialForces: 'Character Skill TroopStrengthSpecialForces',
    TroopStrengthPlanetaryDefense: 'Character Skill TroopStrengthPlanetaryDefense',
    SmugglingIncome: 'Character Skill SmugglingIncome',
    SmugglingEvasion: 'Character Skill SmugglingEvasion',
    BoardingAssault: 'Character Skill BoardingAssault',
} };

/** Galaxy.2.cs 1977-2011 ResolveDescription(CharacterRole): member → GameText tag; other members → string.Empty. */
export const CHARACTER_ROLE: EnumText = { fallback: 'empty', tags: {
    Ambassador: 'Ambassador',
    ColonyGovernor: 'Colony Governor',
    FleetAdmiral: 'Fleet Admiral',
    IntelligenceAgent: 'Intelligence Agent',
    Leader: 'Leader',
    Scientist: 'Scientist',
    TroopGeneral: 'Troop General',
    PirateLeader: 'Pirate Leader',
    ShipCaptain: 'Ship Captain',
} };

/** Galaxy.2.cs 2133-2169 ResolveDescription(BuiltObjectSubRole): member → GameText tag; other members → SplitString(name). */
export const BUILT_OBJECT_SUB_ROLE: EnumText = { fallback: 'split', tags: {
    Carrier: 'Ship SubRole Carrier',
    CapitalShip: 'Ship SubRole CapitalShip',
    ColonyShip: 'Ship SubRole ColonyShip',
    ConstructionShip: 'Ship SubRole ConstructionShip',
    Cruiser: 'Ship SubRole Cruiser',
    DefensiveBase: 'Ship SubRole DefensiveBase',
    Destroyer: 'Ship SubRole Destroyer',
    EnergyResearchStation: 'Ship SubRole EnergyResearchStation',
    Escort: 'Ship SubRole Escort',
    ExplorationShip: 'Ship SubRole ExplorationShip',
    Frigate: 'Ship SubRole Frigate',
    GasMiningShip: 'Ship SubRole GasMiningShip',
    GasMiningStation: 'Ship SubRole GasMiningStation',
    GenericBase: 'Ship SubRole GenericBase',
    HighTechResearchStation: 'Ship SubRole HighTechResearchStation',
    LargeFreighter: 'Ship SubRole LargeFreighter',
    LargeSpacePort: 'Ship SubRole LargeSpacePort',
    MediumFreighter: 'Ship SubRole MediumFreighter',
    MediumSpacePort: 'Ship SubRole MediumSpacePort',
    MiningShip: 'Ship SubRole MiningShip',
    MiningStation: 'Ship SubRole MiningStation',
    MonitoringStation: 'Ship SubRole MonitoringStation',
    PassengerShip: 'Ship SubRole PassengerShip',
    ResortBase: 'Ship SubRole ResortBase',
    ResupplyShip: 'Ship SubRole ResupplyShip',
    SmallFreighter: 'Ship SubRole SmallFreighter',
    SmallSpacePort: 'Ship SubRole SmallSpacePort',
    TroopTransport: 'Ship SubRole TroopTransport',
    WeaponsResearchStation: 'Ship SubRole WeaponsResearchStation',
    Undefined: 'None',
} };

/** Galaxy.2.cs 2472-2486 ResolveDescription(DisasterEventType): member → GameText tag; other members → string.Empty. */
export const DISASTER_EVENT: EnumText = { fallback: 'empty', tags: {
    Blizzard: 'Colony Disaster Blizzard',
    Earthquake: 'Colony Disaster Earthquake',
    EconomicCrisis: 'Empire Disaster Economic Crisis',
    Eruption: 'Colony Disaster Eruption',
    Plague: 'Colony Disaster Plague',
    Sandstorm: 'Colony Disaster Sandstorm',
    Sinkhole: 'Colony Disaster Sinkhole',
    Tsunami: 'Colony Disaster Tsunami',
} };

/** Galaxy.2.cs 2488-2503 ResolveDescription(DiplomaticRelationType): member → GameText tag; other members → SplitString(name). */
export const DIPLOMATIC_RELATION: EnumText = { fallback: 'split', tags: {
    FreeTradeAgreement: 'DiplomaticRelationType FreeTradeAgreement',
    MutualDefensePact: 'DiplomaticRelationType MutualDefensePact',
    None: 'DiplomaticRelationType None',
    NotMet: 'DiplomaticRelationType NotMet',
    Protectorate: 'DiplomaticRelationType Protectorate',
    SubjugatedDominion: 'DiplomaticRelationType SubjugatedDominion',
    TradeSanctions: 'DiplomaticRelationType TradeSanctions',
    Truce: 'DiplomaticRelationType Truce',
    War: 'DiplomaticRelationType War',
} };

/** Galaxy.2.cs 2510-2521 ResolveDescription(HabitatCategoryType): member → GameText tag; other members → SplitString(name). */
export const HABITAT_CATEGORY: EnumText = { fallback: 'split', tags: {
    Asteroid: 'HabitatCategoryType Asteroid',
    GasCloud: 'HabitatCategoryType GasCloud',
    Moon: 'HabitatCategoryType Moon',
    Planet: 'HabitatCategoryType Planet',
    Star: 'HabitatCategoryType Star',
} };

/** Galaxy.2.cs 2523-2555 ResolveDescription(HabitatType): member → GameText tag; other members → SplitString(name). */
export const HABITAT_TYPE: EnumText = { fallback: 'split', tags: {
    Ammonia: 'HabitatType Ammonia',
    Argon: 'HabitatType Argon',
    BarrenRock: 'HabitatType BarrenRock',
    BlackHole: 'HabitatType BlackHole',
    CarbonDioxide: 'HabitatType CarbonDioxide',
    Chlorine: 'HabitatType Chlorine',
    Continental: 'HabitatType Continental',
    Desert: 'HabitatType Desert',
    FrozenGasGiant: 'HabitatType FrozenGasGiant',
    GasGiant: 'HabitatType GasGiant',
    Helium: 'HabitatType Helium',
    Hydrogen: 'HabitatType Hydrogen',
    Ice: 'HabitatType Ice',
    MainSequence: 'HabitatType MainSequence',
    MarshySwamp: 'HabitatType MarshySwamp',
    Metal: 'HabitatType Metal',
    Neutron: 'HabitatType Neutron',
    NitrogenOxygen: 'HabitatType NitrogenOxygen',
    Ocean: 'HabitatType Ocean',
    Oxygen: 'HabitatType Oxygen',
    RedGiant: 'HabitatType RedGiant',
    SuperGiant: 'HabitatType SuperGiant',
    SuperNova: 'HabitatType SuperNova',
    Volcanic: 'HabitatType Volcanic',
    WhiteDwarf: 'HabitatType WhiteDwarf',
    Undefined: 'None',
} };

/** Galaxy.2.cs 2591-2609 ResolveDescription(IntelligenceMissionType): member → GameText tag; other members → SplitString(name). */
export const INTELLIGENCE_MISSION: EnumText = { fallback: 'split', tags: {
    CounterIntelligence: 'IntelligenceMissionType CounterIntelligence',
    DeepCover: 'IntelligenceMissionType DeepCover',
    InciteRevolution: 'IntelligenceMissionType InciteRevolution',
    SabotageColony: 'IntelligenceMissionType SabotageColony',
    SabotageConstruction: 'IntelligenceMissionType SabotageConstruction',
    StealGalaxyMap: 'IntelligenceMissionType StealGalaxyMap',
    StealOperationsMap: 'IntelligenceMissionType StealOperationsMap',
    StealTechData: 'IntelligenceMissionType StealTechData',
    StealTerritoryMap: 'IntelligenceMissionType StealTerritoryMap',
    DestroyBase: 'IntelligenceMissionType DestroyBase',
    AssassinateCharacter: 'IntelligenceMissionType AssassinateCharacter',
    Undefined: 'None',
} };

/** Galaxy.2.cs 2884-2978 ResolveDescription(RaceEventType): member → GameText tag; other members → string.Empty. */
export const RACE_EVENT: EnumText = { fallback: 'empty', tags: {
    AntiXenoRiotsExterminate: 'Race Event Title AntiXenoRiotsExterminate',
    CannibalismPopulationShrinks: 'Race Event Title CannibalismPopulationShrinks',
    CreativeReengineeringFreeCrashResearch: 'Race Event Title CreativeReengineeringFreeCrashResearch',
    DeathCultExterminate: 'Race Event Title DeathCultExterminate',
    DestinyCharacterTraits: 'Race Event Title DestinyCharacterTraits',
    ForcedRetirementLeaderReplaced: 'Race Event Title ForcedRetirementLeaderReplaced',
    FriendsInManyPlacesRevealTerritory: 'Race Event Title FriendsInManyPlacesRevealTerritory',
    GrandPerformanceDiplomacyBonus: 'Race Event Title GrandPerformanceDiplomacyBonus',
    GreatHuntStrongTroops: 'Race Event Title GreatHuntStrongTroops',
    HistoricalDiscoveryExploreRuinsForResearchBoost: 'Race Event Title HistoricalDiscoveryExploreRuinsForResearchBoost',
    HistoricalKnowledgeUncoverHiddenLocation: 'Race Event Title HistoricalKnowledgeUncoverHiddenLocation',
    IsolationistsResetFirstContactPenalty: 'Race Event Title IsolationistsResetFirstContactPenalty',
    LuckyAvertColonyDisaster: 'Race Event Title LuckyAvertColonyDisaster',
    MetamorphosisCharacterChange: 'Race Event Title MetamorphosisCharacterChange',
    NaturalHarmonyColonyQualityIncreased: 'Race Event Title NaturalHarmonyColonyQualityIncreased',
    NepthysWineVintage: 'Race Event Title NepthysWineVintage',
    NeverSurrenderWarWearinessReset: 'Race Event Title NeverSurrenderWarWearinessReset',
    PredictiveHistory: 'Race Event Title PredictiveHistory',
    ScientificBreakthroughResearchProgress: 'Race Event Title ScientificBreakthroughResearchProgress',
    SecurityConcernsCharacterReplaced: 'Race Event Title SecurityConcernsCharacterReplaced',
    ShakturiArtifactWeaponResearch: 'Race Event Title ShakturiArtifactWeaponResearch',
    StrengthInNumbersMaintenanceLowerForSmallShips: 'Race Event Title StrengthInNumbersMaintenanceLowerForSmallShips',
    SuppressedKnowledgeLoseResearch: 'Race Event Title SuppressedKnowledgeLoseResearch',
    SupremeWarriorNewGeneral: 'Race Event Title SupremeWarriorNewGeneral',
    SwarmsFullTroopTransport: 'Race Event Title SwarmsFullTroopTransport',
    TodashGalacticChampionships: 'Race Event Title TodashGalacticChampionships',
    UnderwaterLeviathan: 'Race Event Title UnderwaterLeviathan',
    WarriorWaveTroopRecruitment: 'Race Event Title WarriorWaveTroopRecruitment',
    XenophobiaNoAssimilate: 'Race Event Title XenophobiaNoAssimilate',
} };
/** Galaxy.2.cs ResolveDescription(<enum> member) for the C# member name `name` (undefined: not a member). */
export function resolveEnumTextDescription(table: EnumText, name: string | undefined): string {
    if (name !== undefined) {
        const tag = table.tags[name];
        if (tag !== undefined) return isTextLoaded() ? getText(tag) : tag;
        if (table.fallback === 'split') return splitString(name);
    }
    // switch statement without a case: `string result = string.Empty`; out-of-range value in a switch expression:
    // SplitString(value.ToString()) of a number has no capitals -> "".
    return '';
}
